/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountsummaryGet200Response,
  AccountsummaryGet400Response,
  TransactiondetailsAccountIdGet200Response,
} from '../models/index';
import {
    AccountsummaryGet200ResponseFromJSON,
    AccountsummaryGet200ResponseToJSON,
    AccountsummaryGet400ResponseFromJSON,
    AccountsummaryGet400ResponseToJSON,
    TransactiondetailsAccountIdGet200ResponseFromJSON,
    TransactiondetailsAccountIdGet200ResponseToJSON,
} from '../models/index';

export interface AccountsummaryGetRequest {
    uuid: string;
    clientId: string;
    clientDetails?: string;
}

export interface TransactiondetailsAccountIdGetRequest {
    accountId: string;
    uuid: string;
    clientId: string;
    transactionFromDate?: string;
    transactionToDate?: string;
    clientDetails?: string;
}

/**
 * 
 */
export class AccountsAccountFinancialsAccountTransactionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for accountsummaryGet without sending the request
     */
    async accountsummaryGetRequestOpts(requestParameters: AccountsummaryGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling accountsummaryGet().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling accountsummaryGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['uuid'] != null) {
            headerParameters['uuid'] = String(requestParameters['uuid']);
        }

        if (requestParameters['clientId'] != null) {
            headerParameters['client_id'] = String(requestParameters['clientId']);
        }

        if (requestParameters['clientDetails'] != null) {
            headerParameters['clientDetails'] = String(requestParameters['clientDetails']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/accountsummary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * This API provides the basic details and financial summary of all the accounts belonging to a member/customer
     */
    async accountsummaryGetRaw(requestParameters: AccountsummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountsummaryGet200Response>> {
        const requestOptions = await this.accountsummaryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountsummaryGet200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * This API provides the basic details and financial summary of all the accounts belonging to a member/customer
     */
    async accountsummaryGet(requestParameters: AccountsummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountsummaryGet200Response> {
        const response = await this.accountsummaryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transactiondetailsAccountIdGet without sending the request
     */
    async transactiondetailsAccountIdGetRequestOpts(requestParameters: TransactiondetailsAccountIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling transactiondetailsAccountIdGet().'
            );
        }

        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling transactiondetailsAccountIdGet().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling transactiondetailsAccountIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['transactionFromDate'] != null) {
            queryParameters['transactionFromDate'] = requestParameters['transactionFromDate'];
        }

        if (requestParameters['transactionToDate'] != null) {
            queryParameters['transactionToDate'] = requestParameters['transactionToDate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['uuid'] != null) {
            headerParameters['uuid'] = String(requestParameters['uuid']);
        }

        if (requestParameters['clientId'] != null) {
            headerParameters['client_id'] = String(requestParameters['clientId']);
        }

        if (requestParameters['clientDetails'] != null) {
            headerParameters['clientDetails'] = String(requestParameters['clientDetails']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/transactiondetails/{accountId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * This API gives the list of all the transactions for an account.
     */
    async transactiondetailsAccountIdGetRaw(requestParameters: TransactiondetailsAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactiondetailsAccountIdGet200Response>> {
        const requestOptions = await this.transactiondetailsAccountIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactiondetailsAccountIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * This API gives the list of all the transactions for an account.
     */
    async transactiondetailsAccountIdGet(requestParameters: TransactiondetailsAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactiondetailsAccountIdGet200Response> {
        const response = await this.transactiondetailsAccountIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
