/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner,
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiAccountsTypeAccountIdAccountDetailsPostRequest,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerToJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiAccountsTypeAccountIdAccountDetailsPostRequestFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPostRequestToJSON,
} from '../models/index';

export interface ApiAccountsTypeAccountIdAccountDetailsGetRequest {
    accountsType: ApiAccountsTypeAccountIdAccountDetailsGetAccountsTypeEnum;
    accountId: string;
    afterCursor?: string;
    perPage?: number;
}

export interface ApiAccountsTypeAccountIdAccountDetailsIdDeleteRequest {
    accountsType: ApiAccountsTypeAccountIdAccountDetailsIdDeleteAccountsTypeEnum;
    accountId: string;
    id: string;
}

export interface ApiAccountsTypeAccountIdAccountDetailsIdGetRequest {
    accountsType: ApiAccountsTypeAccountIdAccountDetailsIdGetAccountsTypeEnum;
    accountId: string;
    id: string;
}

export interface ApiAccountsTypeAccountIdAccountDetailsPostOperationRequest {
    accountsType: ApiAccountsTypeAccountIdAccountDetailsPostOperationAccountsTypeEnum;
    accountId: string;
    idempotencyKey?: string;
    apiAccountsTypeAccountIdAccountDetailsPostRequest?: ApiAccountsTypeAccountIdAccountDetailsPostRequest;
}

/**
 * 
 */
export class AccountDetailApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiAccountsTypeAccountIdAccountDetailsGet without sending the request
     */
    async apiAccountsTypeAccountIdAccountDetailsGetRequestOpts(requestParameters: ApiAccountsTypeAccountIdAccountDetailsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountsType'] == null) {
            throw new runtime.RequiredError(
                'accountsType',
                'Required parameter "accountsType" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsGet().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{accounts_type}/{account_id}/account_details`;
        urlPath = urlPath.replace(`{${"accounts_type"}}`, encodeURIComponent(String(requestParameters['accountsType'])));
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * list account_details
     */
    async apiAccountsTypeAccountIdAccountDetailsGetRaw(requestParameters: ApiAccountsTypeAccountIdAccountDetailsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner>>> {
        const requestOptions = await this.apiAccountsTypeAccountIdAccountDetailsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerFromJSON));
    }

    /**
     * N/A
     * list account_details
     */
    async apiAccountsTypeAccountIdAccountDetailsGet(requestParameters: ApiAccountsTypeAccountIdAccountDetailsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner>> {
        const response = await this.apiAccountsTypeAccountIdAccountDetailsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAccountsTypeAccountIdAccountDetailsIdDelete without sending the request
     */
    async apiAccountsTypeAccountIdAccountDetailsIdDeleteRequestOpts(requestParameters: ApiAccountsTypeAccountIdAccountDetailsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountsType'] == null) {
            throw new runtime.RequiredError(
                'accountsType',
                'Required parameter "accountsType" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsIdDelete().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsIdDelete().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{accounts_type}/{account_id}/account_details/{id}`;
        urlPath = urlPath.replace(`{${"accounts_type"}}`, encodeURIComponent(String(requestParameters['accountsType'])));
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * delete account_detail
     */
    async apiAccountsTypeAccountIdAccountDetailsIdDeleteRaw(requestParameters: ApiAccountsTypeAccountIdAccountDetailsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiAccountsTypeAccountIdAccountDetailsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * delete account_detail
     */
    async apiAccountsTypeAccountIdAccountDetailsIdDelete(requestParameters: ApiAccountsTypeAccountIdAccountDetailsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAccountsTypeAccountIdAccountDetailsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiAccountsTypeAccountIdAccountDetailsIdGet without sending the request
     */
    async apiAccountsTypeAccountIdAccountDetailsIdGetRequestOpts(requestParameters: ApiAccountsTypeAccountIdAccountDetailsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountsType'] == null) {
            throw new runtime.RequiredError(
                'accountsType',
                'Required parameter "accountsType" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsIdGet().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsIdGet().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{accounts_type}/{account_id}/account_details/{id}`;
        urlPath = urlPath.replace(`{${"accounts_type"}}`, encodeURIComponent(String(requestParameters['accountsType'])));
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * get account_detail
     */
    async apiAccountsTypeAccountIdAccountDetailsIdGetRaw(requestParameters: ApiAccountsTypeAccountIdAccountDetailsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner>> {
        const requestOptions = await this.apiAccountsTypeAccountIdAccountDetailsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * get account_detail
     */
    async apiAccountsTypeAccountIdAccountDetailsIdGet(requestParameters: ApiAccountsTypeAccountIdAccountDetailsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner> {
        const response = await this.apiAccountsTypeAccountIdAccountDetailsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAccountsTypeAccountIdAccountDetailsPost without sending the request
     */
    async apiAccountsTypeAccountIdAccountDetailsPostRequestOpts(requestParameters: ApiAccountsTypeAccountIdAccountDetailsPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountsType'] == null) {
            throw new runtime.RequiredError(
                'accountsType',
                'Required parameter "accountsType" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsPost().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling apiAccountsTypeAccountIdAccountDetailsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{accounts_type}/{account_id}/account_details`;
        urlPath = urlPath.replace(`{${"accounts_type"}}`, encodeURIComponent(String(requestParameters['accountsType'])));
        urlPath = urlPath.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiAccountsTypeAccountIdAccountDetailsPostRequestToJSON(requestParameters['apiAccountsTypeAccountIdAccountDetailsPostRequest']),
        };
    }

    /**
     * N/A
     * create account_detail
     */
    async apiAccountsTypeAccountIdAccountDetailsPostRaw(requestParameters: ApiAccountsTypeAccountIdAccountDetailsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner>> {
        const requestOptions = await this.apiAccountsTypeAccountIdAccountDetailsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * create account_detail
     */
    async apiAccountsTypeAccountIdAccountDetailsPost(requestParameters: ApiAccountsTypeAccountIdAccountDetailsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner> {
        const response = await this.apiAccountsTypeAccountIdAccountDetailsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiAccountsTypeAccountIdAccountDetailsGetAccountsTypeEnum = {
    ExternalAccounts: 'external_accounts'
} as const;
export type ApiAccountsTypeAccountIdAccountDetailsGetAccountsTypeEnum = typeof ApiAccountsTypeAccountIdAccountDetailsGetAccountsTypeEnum[keyof typeof ApiAccountsTypeAccountIdAccountDetailsGetAccountsTypeEnum];
/**
 * @export
 */
export const ApiAccountsTypeAccountIdAccountDetailsIdDeleteAccountsTypeEnum = {
    ExternalAccounts: 'external_accounts'
} as const;
export type ApiAccountsTypeAccountIdAccountDetailsIdDeleteAccountsTypeEnum = typeof ApiAccountsTypeAccountIdAccountDetailsIdDeleteAccountsTypeEnum[keyof typeof ApiAccountsTypeAccountIdAccountDetailsIdDeleteAccountsTypeEnum];
/**
 * @export
 */
export const ApiAccountsTypeAccountIdAccountDetailsIdGetAccountsTypeEnum = {
    ExternalAccounts: 'external_accounts'
} as const;
export type ApiAccountsTypeAccountIdAccountDetailsIdGetAccountsTypeEnum = typeof ApiAccountsTypeAccountIdAccountDetailsIdGetAccountsTypeEnum[keyof typeof ApiAccountsTypeAccountIdAccountDetailsIdGetAccountsTypeEnum];
/**
 * @export
 */
export const ApiAccountsTypeAccountIdAccountDetailsPostOperationAccountsTypeEnum = {
    ExternalAccounts: 'external_accounts'
} as const;
export type ApiAccountsTypeAccountIdAccountDetailsPostOperationAccountsTypeEnum = typeof ApiAccountsTypeAccountIdAccountDetailsPostOperationAccountsTypeEnum[keyof typeof ApiAccountsTypeAccountIdAccountDetailsPostOperationAccountsTypeEnum];
