/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssetReportAuditCopyCreatePost200Response,
  AssetReportCreatePost200Response,
  AssetReportGetPost200Response,
  ItemRemovePost200Response,
} from '../models/index';
import {
    AssetReportAuditCopyCreatePost200ResponseFromJSON,
    AssetReportAuditCopyCreatePost200ResponseToJSON,
    AssetReportCreatePost200ResponseFromJSON,
    AssetReportCreatePost200ResponseToJSON,
    AssetReportGetPost200ResponseFromJSON,
    AssetReportGetPost200ResponseToJSON,
    ItemRemovePost200ResponseFromJSON,
    ItemRemovePost200ResponseToJSON,
} from '../models/index';

export interface InvestmentsAssetsSearchGetRequest {
    query?: string;
    minESGScore?: number;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class AssetsApi extends runtime.BaseAPI {

    /**
     * Creates request options for assetReportAuditCopyCreatePost without sending the request
     */
    async assetReportAuditCopyCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/asset_report/audit_copy/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Create Audit Copy
     */
    async assetReportAuditCopyCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssetReportAuditCopyCreatePost200Response>> {
        const requestOptions = await this.assetReportAuditCopyCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetReportAuditCopyCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Create Audit Copy
     */
    async assetReportAuditCopyCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssetReportAuditCopyCreatePost200Response> {
        const response = await this.assetReportAuditCopyCreatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for assetReportAuditCopyRemovePost without sending the request
     */
    async assetReportAuditCopyRemovePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/asset_report/audit_copy/remove`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Remove Audit Copy 
     */
    async assetReportAuditCopyRemovePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemRemovePost200Response>> {
        const requestOptions = await this.assetReportAuditCopyRemovePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemRemovePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Remove Audit Copy 
     */
    async assetReportAuditCopyRemovePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemRemovePost200Response> {
        const response = await this.assetReportAuditCopyRemovePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for assetReportCreatePost without sending the request
     */
    async assetReportCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/asset_report/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Create Asset Report
     */
    async assetReportCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssetReportCreatePost200Response>> {
        const requestOptions = await this.assetReportCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetReportCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Create Asset Report
     */
    async assetReportCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssetReportCreatePost200Response> {
        const response = await this.assetReportCreatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for assetReportGetPost without sending the request
     */
    async assetReportGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/asset_report/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Retrieve an Asset Report (JSON)
     */
    async assetReportGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssetReportGetPost200Response>> {
        const requestOptions = await this.assetReportGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetReportGetPost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Retrieve an Asset Report (JSON)
     */
    async assetReportGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssetReportGetPost200Response> {
        const response = await this.assetReportGetPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for assetReportPdfGetPost without sending the request
     */
    async assetReportPdfGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/asset_report/pdf/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Retrieve an Asset Report (PDF)
     */
    async assetReportPdfGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.assetReportPdfGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * Retrieve an Asset Report (PDF)
     */
    async assetReportPdfGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.assetReportPdfGetPostRaw(initOverrides);
    }

    /**
     * Creates request options for assetReportRefreshPost without sending the request
     */
    async assetReportRefreshPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/asset_report/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Refresh Asset Report 
     */
    async assetReportRefreshPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssetReportCreatePost200Response>> {
        const requestOptions = await this.assetReportRefreshPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetReportCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Refresh Asset Report 
     */
    async assetReportRefreshPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssetReportCreatePost200Response> {
        const response = await this.assetReportRefreshPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for assetReportRemovePost without sending the request
     */
    async assetReportRemovePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/asset_report/remove`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Remove Asset Report
     */
    async assetReportRemovePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemRemovePost200Response>> {
        const requestOptions = await this.assetReportRemovePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemRemovePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Remove Asset Report
     */
    async assetReportRemovePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemRemovePost200Response> {
        const response = await this.assetReportRemovePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for investmentsAssetsSearchGet without sending the request
     */
    async investmentsAssetsSearchGetRequestOpts(requestParameters: InvestmentsAssetsSearchGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['minESGScore'] != null) {
            queryParameters['minESGScore'] = requestParameters['minESGScore'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/investments/assets/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Search for Investment Assets with ESG Scores
     */
    async investmentsAssetsSearchGetRaw(requestParameters: InvestmentsAssetsSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.investmentsAssetsSearchGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * N/A
     * Search for Investment Assets with ESG Scores
     */
    async investmentsAssetsSearchGet(requestParameters: InvestmentsAssetsSearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.investmentsAssetsSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
