/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInner,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInnerFromJSON,
    ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInnerToJSON,
} from '../models/index';

export interface ApiInternalAccountsInternalAccountIdBalanceReportsGetRequest {
    internalAccountId: string;
    asOfDate?: Date;
    balanceReportType?: ApiInternalAccountsInternalAccountIdBalanceReportsGetBalanceReportTypeEnum;
    afterCursor?: string;
    perPage?: number;
}

export interface ApiInternalAccountsInternalAccountIdBalanceReportsIdGetRequest {
    internalAccountId: string;
    id: string;
}

/**
 * 
 */
export class BalanceReportApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiInternalAccountsInternalAccountIdBalanceReportsGet without sending the request
     */
    async apiInternalAccountsInternalAccountIdBalanceReportsGetRequestOpts(requestParameters: ApiInternalAccountsInternalAccountIdBalanceReportsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['internalAccountId'] == null) {
            throw new runtime.RequiredError(
                'internalAccountId',
                'Required parameter "internalAccountId" was null or undefined when calling apiInternalAccountsInternalAccountIdBalanceReportsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['asOfDate'] != null) {
            queryParameters['as_of_date'] = (requestParameters['asOfDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['balanceReportType'] != null) {
            queryParameters['balance_report_type'] = requestParameters['balanceReportType'];
        }

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/internal_accounts/{internal_account_id}/balance_reports`;
        urlPath = urlPath.replace(`{${"internal_account_id"}}`, encodeURIComponent(String(requestParameters['internalAccountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * list balance_reports
     */
    async apiInternalAccountsInternalAccountIdBalanceReportsGetRaw(requestParameters: ApiInternalAccountsInternalAccountIdBalanceReportsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInner>>> {
        const requestOptions = await this.apiInternalAccountsInternalAccountIdBalanceReportsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInnerFromJSON));
    }

    /**
     * N/A
     * list balance_reports
     */
    async apiInternalAccountsInternalAccountIdBalanceReportsGet(requestParameters: ApiInternalAccountsInternalAccountIdBalanceReportsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInner>> {
        const response = await this.apiInternalAccountsInternalAccountIdBalanceReportsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiInternalAccountsInternalAccountIdBalanceReportsIdGet without sending the request
     */
    async apiInternalAccountsInternalAccountIdBalanceReportsIdGetRequestOpts(requestParameters: ApiInternalAccountsInternalAccountIdBalanceReportsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['internalAccountId'] == null) {
            throw new runtime.RequiredError(
                'internalAccountId',
                'Required parameter "internalAccountId" was null or undefined when calling apiInternalAccountsInternalAccountIdBalanceReportsIdGet().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiInternalAccountsInternalAccountIdBalanceReportsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/internal_accounts/{internal_account_id}/balance_reports/{id}`;
        urlPath = urlPath.replace(`{${"internal_account_id"}}`, encodeURIComponent(String(requestParameters['internalAccountId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * get balance_report
     */
    async apiInternalAccountsInternalAccountIdBalanceReportsIdGetRaw(requestParameters: ApiInternalAccountsInternalAccountIdBalanceReportsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInner>> {
        const requestOptions = await this.apiInternalAccountsInternalAccountIdBalanceReportsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * get balance_report
     */
    async apiInternalAccountsInternalAccountIdBalanceReportsIdGet(requestParameters: ApiInternalAccountsInternalAccountIdBalanceReportsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiInternalAccountsInternalAccountIdBalanceReportsGet200ResponseInner> {
        const response = await this.apiInternalAccountsInternalAccountIdBalanceReportsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiInternalAccountsInternalAccountIdBalanceReportsGetBalanceReportTypeEnum = {
    Intraday: 'intraday',
    Other: 'other',
    PreviousDay: 'previous_day',
    RealTime: 'real_time'
} as const;
export type ApiInternalAccountsInternalAccountIdBalanceReportsGetBalanceReportTypeEnum = typeof ApiInternalAccountsInternalAccountIdBalanceReportsGetBalanceReportTypeEnum[keyof typeof ApiInternalAccountsInternalAccountIdBalanceReportsGetBalanceReportTypeEnum];
