/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BudgetsBudgetIdGet200Response,
  BudgetsBudgetIdPut200Response,
  BudgetsBudgetIdPutRequest,
  BudgetsGet200Response,
  UsersRegisterPost400Response,
} from '../models/index';
import {
    BudgetsBudgetIdGet200ResponseFromJSON,
    BudgetsBudgetIdGet200ResponseToJSON,
    BudgetsBudgetIdPut200ResponseFromJSON,
    BudgetsBudgetIdPut200ResponseToJSON,
    BudgetsBudgetIdPutRequestFromJSON,
    BudgetsBudgetIdPutRequestToJSON,
    BudgetsGet200ResponseFromJSON,
    BudgetsGet200ResponseToJSON,
    UsersRegisterPost400ResponseFromJSON,
    UsersRegisterPost400ResponseToJSON,
} from '../models/index';

export interface BudgetsBudgetIdGetRequest {
    budgetId: string;
}

export interface BudgetsBudgetIdPutOperationRequest {
    budgetId: string;
    budgetsBudgetIdPutRequest?: BudgetsBudgetIdPutRequest;
}

export interface BudgetsGetRequest {
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class BudgetsApi extends runtime.BaseAPI {

    /**
     * Creates request options for budgetsBudgetIdGet without sending the request
     */
    async budgetsBudgetIdGetRequestOpts(requestParameters: BudgetsBudgetIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['budgetId'] == null) {
            throw new runtime.RequiredError(
                'budgetId',
                'Required parameter "budgetId" was null or undefined when calling budgetsBudgetIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/budgets/{budgetId}`;
        urlPath = urlPath.replace(`{${"budgetId"}}`, encodeURIComponent(String(requestParameters['budgetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get Detailed Budget Information
     */
    async budgetsBudgetIdGetRaw(requestParameters: BudgetsBudgetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BudgetsBudgetIdGet200Response>> {
        const requestOptions = await this.budgetsBudgetIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BudgetsBudgetIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Get Detailed Budget Information
     */
    async budgetsBudgetIdGet(requestParameters: BudgetsBudgetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BudgetsBudgetIdGet200Response> {
        const response = await this.budgetsBudgetIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for budgetsBudgetIdPut without sending the request
     */
    async budgetsBudgetIdPutRequestOpts(requestParameters: BudgetsBudgetIdPutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['budgetId'] == null) {
            throw new runtime.RequiredError(
                'budgetId',
                'Required parameter "budgetId" was null or undefined when calling budgetsBudgetIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/budgets/{budgetId}`;
        urlPath = urlPath.replace(`{${"budgetId"}}`, encodeURIComponent(String(requestParameters['budgetId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BudgetsBudgetIdPutRequestToJSON(requestParameters['budgetsBudgetIdPutRequest']),
        };
    }

    /**
     * N/A
     * Update an Existing Budget
     */
    async budgetsBudgetIdPutRaw(requestParameters: BudgetsBudgetIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BudgetsBudgetIdPut200Response>> {
        const requestOptions = await this.budgetsBudgetIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BudgetsBudgetIdPut200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Update an Existing Budget
     */
    async budgetsBudgetIdPut(requestParameters: BudgetsBudgetIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BudgetsBudgetIdPut200Response> {
        const response = await this.budgetsBudgetIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for budgetsGet without sending the request
     */
    async budgetsGetRequestOpts(requestParameters: BudgetsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/budgets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * List All User Budgets
     */
    async budgetsGetRaw(requestParameters: BudgetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BudgetsGet200Response>> {
        const requestOptions = await this.budgetsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BudgetsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * List All User Budgets
     */
    async budgetsGet(requestParameters: BudgetsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BudgetsGet200Response> {
        const response = await this.budgetsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
