/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiDocumentsGet200ResponseInner,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiDocumentsGet200ResponseInnerFromJSON,
    ApiDocumentsGet200ResponseInnerToJSON,
} from '../models/index';

export interface ApiDocumentableTypeDocumentableIdDocumentsGetRequest {
    documentableType: ApiDocumentableTypeDocumentableIdDocumentsGetDocumentableTypeEnum;
    documentableId: string;
    documentType?: string;
    afterCursor?: string;
    perPage?: number;
}

export interface ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRequest {
    documentableType: ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetDocumentableTypeEnum;
    documentableId: string;
    id: string;
}

export interface ApiDocumentableTypeDocumentableIdDocumentsIdGetRequest {
    documentableType: ApiDocumentableTypeDocumentableIdDocumentsIdGetDocumentableTypeEnum;
    documentableId: string;
    id: string;
}

export interface ApiDocumentableTypeDocumentableIdDocumentsPostRequest {
    documentableType: ApiDocumentableTypeDocumentableIdDocumentsPostDocumentableTypeEnum;
    documentableId: string;
    idempotencyKey?: string;
}

export interface ApiDocumentsGetRequest {
    documentableId?: string;
    documentableType?: ApiDocumentsGetDocumentableTypeEnum;
    afterCursor?: string;
    perPage?: number;
}

export interface ApiDocumentsIdDownloadGetRequest {
    id: string;
}

export interface ApiDocumentsIdGetRequest {
    id: string;
}

export interface ApiDocumentsPostRequest {
    idempotencyKey?: string;
}

/**
 * 
 */
export class DocumentApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiDocumentableTypeDocumentableIdDocumentsGet without sending the request
     */
    async apiDocumentableTypeDocumentableIdDocumentsGetRequestOpts(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['documentableType'] == null) {
            throw new runtime.RequiredError(
                'documentableType',
                'Required parameter "documentableType" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsGet().'
            );
        }

        if (requestParameters['documentableId'] == null) {
            throw new runtime.RequiredError(
                'documentableId',
                'Required parameter "documentableId" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['documentType'] != null) {
            queryParameters['document_type'] = requestParameters['documentType'];
        }

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{documentable_type}/{documentable_id}/documents`;
        urlPath = urlPath.replace(`{${"documentable_type"}}`, encodeURIComponent(String(requestParameters['documentableType'])));
        urlPath = urlPath.replace(`{${"documentable_id"}}`, encodeURIComponent(String(requestParameters['documentableId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * list documents - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsGetRaw(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDocumentsGet200ResponseInner>>> {
        const requestOptions = await this.apiDocumentableTypeDocumentableIdDocumentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiDocumentsGet200ResponseInnerFromJSON));
    }

    /**
     * N/A
     * list documents - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsGet(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDocumentsGet200ResponseInner>> {
        const response = await this.apiDocumentableTypeDocumentableIdDocumentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDocumentableTypeDocumentableIdDocumentsIdDownloadGet without sending the request
     */
    async apiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRequestOpts(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['documentableType'] == null) {
            throw new runtime.RequiredError(
                'documentableType',
                'Required parameter "documentableType" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsIdDownloadGet().'
            );
        }

        if (requestParameters['documentableId'] == null) {
            throw new runtime.RequiredError(
                'documentableId',
                'Required parameter "documentableId" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsIdDownloadGet().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsIdDownloadGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{documentable_type}/{documentable_id}/documents/{id}/download`;
        urlPath = urlPath.replace(`{${"documentable_type"}}`, encodeURIComponent(String(requestParameters['documentableType'])));
        urlPath = urlPath.replace(`{${"documentable_id"}}`, encodeURIComponent(String(requestParameters['documentableId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * download document - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRaw(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * download document - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsIdDownloadGet(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDocumentableTypeDocumentableIdDocumentsIdDownloadGetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiDocumentableTypeDocumentableIdDocumentsIdGet without sending the request
     */
    async apiDocumentableTypeDocumentableIdDocumentsIdGetRequestOpts(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['documentableType'] == null) {
            throw new runtime.RequiredError(
                'documentableType',
                'Required parameter "documentableType" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsIdGet().'
            );
        }

        if (requestParameters['documentableId'] == null) {
            throw new runtime.RequiredError(
                'documentableId',
                'Required parameter "documentableId" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsIdGet().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{documentable_type}/{documentable_id}/documents/{id}`;
        urlPath = urlPath.replace(`{${"documentable_type"}}`, encodeURIComponent(String(requestParameters['documentableType'])));
        urlPath = urlPath.replace(`{${"documentable_id"}}`, encodeURIComponent(String(requestParameters['documentableId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * get document - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsIdGetRaw(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDocumentsGet200ResponseInner>> {
        const requestOptions = await this.apiDocumentableTypeDocumentableIdDocumentsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDocumentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * get document - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsIdGet(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDocumentsGet200ResponseInner> {
        const response = await this.apiDocumentableTypeDocumentableIdDocumentsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDocumentableTypeDocumentableIdDocumentsPost without sending the request
     */
    async apiDocumentableTypeDocumentableIdDocumentsPostRequestOpts(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['documentableType'] == null) {
            throw new runtime.RequiredError(
                'documentableType',
                'Required parameter "documentableType" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsPost().'
            );
        }

        if (requestParameters['documentableId'] == null) {
            throw new runtime.RequiredError(
                'documentableId',
                'Required parameter "documentableId" was null or undefined when calling apiDocumentableTypeDocumentableIdDocumentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/{documentable_type}/{documentable_id}/documents`;
        urlPath = urlPath.replace(`{${"documentable_type"}}`, encodeURIComponent(String(requestParameters['documentableType'])));
        urlPath = urlPath.replace(`{${"documentable_id"}}`, encodeURIComponent(String(requestParameters['documentableId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * create document - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsPostRaw(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDocumentsGet200ResponseInner>> {
        const requestOptions = await this.apiDocumentableTypeDocumentableIdDocumentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDocumentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * create document - nested path (legacy)
     */
    async apiDocumentableTypeDocumentableIdDocumentsPost(requestParameters: ApiDocumentableTypeDocumentableIdDocumentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDocumentsGet200ResponseInner> {
        const response = await this.apiDocumentableTypeDocumentableIdDocumentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDocumentsGet without sending the request
     */
    async apiDocumentsGetRequestOpts(requestParameters: ApiDocumentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['documentableId'] != null) {
            queryParameters['documentable_id'] = requestParameters['documentableId'];
        }

        if (requestParameters['documentableType'] != null) {
            queryParameters['documentable_type'] = requestParameters['documentableType'];
        }

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/documents`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * list documents
     */
    async apiDocumentsGetRaw(requestParameters: ApiDocumentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDocumentsGet200ResponseInner>>> {
        const requestOptions = await this.apiDocumentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiDocumentsGet200ResponseInnerFromJSON));
    }

    /**
     * N/A
     * list documents
     */
    async apiDocumentsGet(requestParameters: ApiDocumentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDocumentsGet200ResponseInner>> {
        const response = await this.apiDocumentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDocumentsIdDownloadGet without sending the request
     */
    async apiDocumentsIdDownloadGetRequestOpts(requestParameters: ApiDocumentsIdDownloadGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDocumentsIdDownloadGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/documents/{id}/download`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * download document
     */
    async apiDocumentsIdDownloadGetRaw(requestParameters: ApiDocumentsIdDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiDocumentsIdDownloadGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * download document
     */
    async apiDocumentsIdDownloadGet(requestParameters: ApiDocumentsIdDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDocumentsIdDownloadGetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiDocumentsIdGet without sending the request
     */
    async apiDocumentsIdGetRequestOpts(requestParameters: ApiDocumentsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDocumentsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/documents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * get document
     */
    async apiDocumentsIdGetRaw(requestParameters: ApiDocumentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDocumentsGet200ResponseInner>> {
        const requestOptions = await this.apiDocumentsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDocumentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * get document
     */
    async apiDocumentsIdGet(requestParameters: ApiDocumentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDocumentsGet200ResponseInner> {
        const response = await this.apiDocumentsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDocumentsPost without sending the request
     */
    async apiDocumentsPostRequestOpts(requestParameters: ApiDocumentsPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/documents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * create document
     */
    async apiDocumentsPostRaw(requestParameters: ApiDocumentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDocumentsGet200ResponseInner>> {
        const requestOptions = await this.apiDocumentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDocumentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * create document
     */
    async apiDocumentsPost(requestParameters: ApiDocumentsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDocumentsGet200ResponseInner> {
        const response = await this.apiDocumentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiDocumentableTypeDocumentableIdDocumentsGetDocumentableTypeEnum = {
    Cases: 'cases',
    Counterparties: 'counterparties',
    ExpectedPayments: 'expected_payments',
    ExternalAccounts: 'external_accounts',
    InternalAccounts: 'internal_accounts',
    Organizations: 'organizations',
    PaperItems: 'paper_items',
    PaymentOrders: 'payment_orders',
    Transactions: 'transactions',
    Decisions: 'decisions',
    Connections: 'connections'
} as const;
export type ApiDocumentableTypeDocumentableIdDocumentsGetDocumentableTypeEnum = typeof ApiDocumentableTypeDocumentableIdDocumentsGetDocumentableTypeEnum[keyof typeof ApiDocumentableTypeDocumentableIdDocumentsGetDocumentableTypeEnum];
/**
 * @export
 */
export const ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetDocumentableTypeEnum = {
    Cases: 'cases',
    Counterparties: 'counterparties',
    ExpectedPayments: 'expected_payments',
    ExternalAccounts: 'external_accounts',
    InternalAccounts: 'internal_accounts',
    Organizations: 'organizations',
    PaperItems: 'paper_items',
    PaymentOrders: 'payment_orders',
    Transactions: 'transactions',
    Decisions: 'decisions',
    Connections: 'connections'
} as const;
export type ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetDocumentableTypeEnum = typeof ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetDocumentableTypeEnum[keyof typeof ApiDocumentableTypeDocumentableIdDocumentsIdDownloadGetDocumentableTypeEnum];
/**
 * @export
 */
export const ApiDocumentableTypeDocumentableIdDocumentsIdGetDocumentableTypeEnum = {
    Cases: 'cases',
    Counterparties: 'counterparties',
    ExpectedPayments: 'expected_payments',
    ExternalAccounts: 'external_accounts',
    InternalAccounts: 'internal_accounts',
    Organizations: 'organizations',
    PaperItems: 'paper_items',
    PaymentOrders: 'payment_orders',
    Transactions: 'transactions',
    Decisions: 'decisions',
    Connections: 'connections'
} as const;
export type ApiDocumentableTypeDocumentableIdDocumentsIdGetDocumentableTypeEnum = typeof ApiDocumentableTypeDocumentableIdDocumentsIdGetDocumentableTypeEnum[keyof typeof ApiDocumentableTypeDocumentableIdDocumentsIdGetDocumentableTypeEnum];
/**
 * @export
 */
export const ApiDocumentableTypeDocumentableIdDocumentsPostDocumentableTypeEnum = {
    Cases: 'cases',
    Counterparties: 'counterparties',
    ExpectedPayments: 'expected_payments',
    ExternalAccounts: 'external_accounts',
    InternalAccounts: 'internal_accounts',
    Organizations: 'organizations',
    PaperItems: 'paper_items',
    PaymentOrders: 'payment_orders',
    Transactions: 'transactions',
    Decisions: 'decisions',
    Connections: 'connections'
} as const;
export type ApiDocumentableTypeDocumentableIdDocumentsPostDocumentableTypeEnum = typeof ApiDocumentableTypeDocumentableIdDocumentsPostDocumentableTypeEnum[keyof typeof ApiDocumentableTypeDocumentableIdDocumentsPostDocumentableTypeEnum];
/**
 * @export
 */
export const ApiDocumentsGetDocumentableTypeEnum = {
    Cases: 'cases',
    Counterparties: 'counterparties',
    ExpectedPayments: 'expected_payments',
    ExternalAccounts: 'external_accounts',
    InternalAccounts: 'internal_accounts',
    Organizations: 'organizations',
    PaperItems: 'paper_items',
    PaymentOrders: 'payment_orders',
    Transactions: 'transactions',
    Decisions: 'decisions',
    Connections: 'connections'
} as const;
export type ApiDocumentsGetDocumentableTypeEnum = typeof ApiDocumentsGetDocumentableTypeEnum[keyof typeof ApiDocumentsGetDocumentableTypeEnum];
