/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiEventsGet200ResponseInner,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiEventsGet200ResponseInnerFromJSON,
    ApiEventsGet200ResponseInnerToJSON,
} from '../models/index';

export interface ApiEventsGetRequest {
    afterCursor?: string;
    perPage?: number;
    eventTimeStart?: Date;
    eventTimeEnd?: Date;
    resource?: string;
    entityId?: string;
    eventName?: string;
}

export interface ApiEventsIdGetRequest {
    id: string;
}

/**
 * 
 */
export class EventApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiEventsGet without sending the request
     */
    async apiEventsGetRequestOpts(requestParameters: ApiEventsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['eventTimeStart'] != null) {
            queryParameters['event_time_start'] = (requestParameters['eventTimeStart'] as any).toISOString();
        }

        if (requestParameters['eventTimeEnd'] != null) {
            queryParameters['event_time_end'] = (requestParameters['eventTimeEnd'] as any).toISOString();
        }

        if (requestParameters['resource'] != null) {
            queryParameters['resource'] = requestParameters['resource'];
        }

        if (requestParameters['entityId'] != null) {
            queryParameters['entity_id'] = requestParameters['entityId'];
        }

        if (requestParameters['eventName'] != null) {
            queryParameters['event_name'] = requestParameters['eventName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list events
     */
    async apiEventsGetRaw(requestParameters: ApiEventsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiEventsGet200ResponseInner>>> {
        const requestOptions = await this.apiEventsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiEventsGet200ResponseInnerFromJSON));
    }

    /**
     * list events
     */
    async apiEventsGet(requestParameters: ApiEventsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiEventsGet200ResponseInner>> {
        const response = await this.apiEventsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiEventsIdGet without sending the request
     */
    async apiEventsIdGetRequestOpts(requestParameters: ApiEventsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiEventsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/events/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get event
     */
    async apiEventsIdGetRaw(requestParameters: ApiEventsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEventsGet200ResponseInner>> {
        const requestOptions = await this.apiEventsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEventsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * get event
     */
    async apiEventsIdGet(requestParameters: ApiEventsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEventsGet200ResponseInner> {
        const response = await this.apiEventsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
