/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiExpectedPaymentsGet200ResponseInner,
  ApiExpectedPaymentsIdPatchRequest,
  ApiExpectedPaymentsPostRequest,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiExpectedPaymentsGet200ResponseInnerFromJSON,
    ApiExpectedPaymentsGet200ResponseInnerToJSON,
    ApiExpectedPaymentsIdPatchRequestFromJSON,
    ApiExpectedPaymentsIdPatchRequestToJSON,
    ApiExpectedPaymentsPostRequestFromJSON,
    ApiExpectedPaymentsPostRequestToJSON,
} from '../models/index';

export interface ApiExpectedPaymentsGetRequest {
    afterCursor?: string;
    perPage?: number;
    status?: ApiExpectedPaymentsGetStatusEnum;
    internalAccountId?: string;
    direction?: ApiExpectedPaymentsGetDirectionEnum;
    type?: ApiExpectedPaymentsGetTypeEnum;
    counterpartyId?: string;
    metadataKey0?: string;
    createdAtLowerBound?: Date;
    createdAtUpperBound?: Date;
}

export interface ApiExpectedPaymentsIdDeleteRequest {
    id: string;
}

export interface ApiExpectedPaymentsIdGetRequest {
    id: string;
}

export interface ApiExpectedPaymentsIdPatchOperationRequest {
    id: string;
    apiExpectedPaymentsIdPatchRequest?: ApiExpectedPaymentsIdPatchRequest;
}

export interface ApiExpectedPaymentsPostOperationRequest {
    idempotencyKey?: string;
    apiExpectedPaymentsPostRequest?: ApiExpectedPaymentsPostRequest;
}

/**
 * 
 */
export class ExpectedPaymentApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiExpectedPaymentsGet without sending the request
     */
    async apiExpectedPaymentsGetRequestOpts(requestParameters: ApiExpectedPaymentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['internalAccountId'] != null) {
            queryParameters['internal_account_id'] = requestParameters['internalAccountId'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['counterpartyId'] != null) {
            queryParameters['counterparty_id'] = requestParameters['counterpartyId'];
        }

        if (requestParameters['metadataKey0'] != null) {
            queryParameters['metadata[key_0]'] = requestParameters['metadataKey0'];
        }

        if (requestParameters['createdAtLowerBound'] != null) {
            queryParameters['created_at_lower_bound'] = (requestParameters['createdAtLowerBound'] as any).toISOString();
        }

        if (requestParameters['createdAtUpperBound'] != null) {
            queryParameters['created_at_upper_bound'] = (requestParameters['createdAtUpperBound'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/expected_payments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list expected_payments
     */
    async apiExpectedPaymentsGetRaw(requestParameters: ApiExpectedPaymentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiExpectedPaymentsGet200ResponseInner>>> {
        const requestOptions = await this.apiExpectedPaymentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiExpectedPaymentsGet200ResponseInnerFromJSON));
    }

    /**
     * list expected_payments
     */
    async apiExpectedPaymentsGet(requestParameters: ApiExpectedPaymentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiExpectedPaymentsGet200ResponseInner>> {
        const response = await this.apiExpectedPaymentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiExpectedPaymentsIdDelete without sending the request
     */
    async apiExpectedPaymentsIdDeleteRequestOpts(requestParameters: ApiExpectedPaymentsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiExpectedPaymentsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/expected_payments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * delete expected payment
     */
    async apiExpectedPaymentsIdDeleteRaw(requestParameters: ApiExpectedPaymentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiExpectedPaymentsGet200ResponseInner>> {
        const requestOptions = await this.apiExpectedPaymentsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiExpectedPaymentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * delete expected payment
     */
    async apiExpectedPaymentsIdDelete(requestParameters: ApiExpectedPaymentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiExpectedPaymentsGet200ResponseInner> {
        const response = await this.apiExpectedPaymentsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiExpectedPaymentsIdGet without sending the request
     */
    async apiExpectedPaymentsIdGetRequestOpts(requestParameters: ApiExpectedPaymentsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiExpectedPaymentsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/expected_payments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get expected payment
     */
    async apiExpectedPaymentsIdGetRaw(requestParameters: ApiExpectedPaymentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiExpectedPaymentsGet200ResponseInner>> {
        const requestOptions = await this.apiExpectedPaymentsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiExpectedPaymentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * get expected payment
     */
    async apiExpectedPaymentsIdGet(requestParameters: ApiExpectedPaymentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiExpectedPaymentsGet200ResponseInner> {
        const response = await this.apiExpectedPaymentsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiExpectedPaymentsIdPatch without sending the request
     */
    async apiExpectedPaymentsIdPatchRequestOpts(requestParameters: ApiExpectedPaymentsIdPatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiExpectedPaymentsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/expected_payments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ApiExpectedPaymentsIdPatchRequestToJSON(requestParameters['apiExpectedPaymentsIdPatchRequest']),
        };
    }

    /**
     * update expected payment
     */
    async apiExpectedPaymentsIdPatchRaw(requestParameters: ApiExpectedPaymentsIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiExpectedPaymentsGet200ResponseInner>> {
        const requestOptions = await this.apiExpectedPaymentsIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiExpectedPaymentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * update expected payment
     */
    async apiExpectedPaymentsIdPatch(requestParameters: ApiExpectedPaymentsIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiExpectedPaymentsGet200ResponseInner> {
        const response = await this.apiExpectedPaymentsIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiExpectedPaymentsPost without sending the request
     */
    async apiExpectedPaymentsPostRequestOpts(requestParameters: ApiExpectedPaymentsPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/expected_payments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiExpectedPaymentsPostRequestToJSON(requestParameters['apiExpectedPaymentsPostRequest']),
        };
    }

    /**
     * create expected payment
     */
    async apiExpectedPaymentsPostRaw(requestParameters: ApiExpectedPaymentsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiExpectedPaymentsGet200ResponseInner>> {
        const requestOptions = await this.apiExpectedPaymentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiExpectedPaymentsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * create expected payment
     */
    async apiExpectedPaymentsPost(requestParameters: ApiExpectedPaymentsPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiExpectedPaymentsGet200ResponseInner> {
        const response = await this.apiExpectedPaymentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiExpectedPaymentsGetStatusEnum = {
    Archived: 'archived',
    PartiallyReconciled: 'partially_reconciled',
    Reconciled: 'reconciled',
    Unreconciled: 'unreconciled'
} as const;
export type ApiExpectedPaymentsGetStatusEnum = typeof ApiExpectedPaymentsGetStatusEnum[keyof typeof ApiExpectedPaymentsGetStatusEnum];
/**
 * @export
 */
export const ApiExpectedPaymentsGetDirectionEnum = {
    Credit: 'credit',
    Debit: 'debit'
} as const;
export type ApiExpectedPaymentsGetDirectionEnum = typeof ApiExpectedPaymentsGetDirectionEnum[keyof typeof ApiExpectedPaymentsGetDirectionEnum];
/**
 * @export
 */
export const ApiExpectedPaymentsGetTypeEnum = {
    Ach: 'ach',
    AuBecs: 'au_becs',
    Bacs: 'bacs',
    Book: 'book',
    Card: 'card',
    Check: 'check',
    CrossBorder: 'cross_border',
    Eft: 'eft',
    Interac: 'interac',
    Masav: 'masav',
    Neft: 'neft',
    Nics: 'nics',
    Provxchange: 'provxchange',
    Rtp: 'rtp',
    SeBankgirot: 'se_bankgirot',
    Sen: 'sen',
    Sepa: 'sepa',
    Sic: 'sic',
    Signet: 'signet',
    Wire: 'wire',
    Zengin: 'zengin'
} as const;
export type ApiExpectedPaymentsGetTypeEnum = typeof ApiExpectedPaymentsGetTypeEnum[keyof typeof ApiExpectedPaymentsGetTypeEnum];
