/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AiIncubatorPitchPitchIdFeedbackPutRequest {
    pitchId: string;
    body?: object;
}

/**
 * 
 */
export class FeedbackApi extends runtime.BaseAPI {

    /**
     * Creates request options for aiIncubatorPitchPitchIdFeedbackPut without sending the request
     */
    async aiIncubatorPitchPitchIdFeedbackPutRequestOpts(requestParameters: AiIncubatorPitchPitchIdFeedbackPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pitchId'] == null) {
            throw new runtime.RequiredError(
                'pitchId',
                'Required parameter "pitchId" was null or undefined when calling aiIncubatorPitchPitchIdFeedbackPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/ai/incubator/pitch/{pitchId}/feedback`;
        urlPath = urlPath.replace(`{${"pitchId"}}`, encodeURIComponent(String(requestParameters['pitchId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * N/A
     * Submit Feedback or Answers to AI Questions for a Business Pitch
     */
    async aiIncubatorPitchPitchIdFeedbackPutRaw(requestParameters: AiIncubatorPitchPitchIdFeedbackPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.aiIncubatorPitchPitchIdFeedbackPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * N/A
     * Submit Feedback or Answers to AI Questions for a Business Pitch
     */
    async aiIncubatorPitchPitchIdFeedbackPut(requestParameters: AiIncubatorPitchPitchIdFeedbackPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.aiIncubatorPitchPitchIdFeedbackPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
