/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AiAdsGeneratePostRequest {
    body?: object;
}

/**
 * 
 */
export class GenerateApi extends runtime.BaseAPI {

    /**
     * Creates request options for aiAdsGeneratePost without sending the request
     */
    async aiAdsGeneratePostRequestOpts(requestParameters: AiAdsGeneratePostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/ai/ads/generate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * N/A
     * Generate a Standard Video Ad with Veo 2.0
     */
    async aiAdsGeneratePostRaw(requestParameters: AiAdsGeneratePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.aiAdsGeneratePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * N/A
     * Generate a Standard Video Ad with Veo 2.0
     */
    async aiAdsGeneratePost(requestParameters: AiAdsGeneratePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.aiAdsGeneratePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
