/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AiAdvisorChatHistoryGetRequest {
    sessionId?: string;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class HistoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for aiAdvisorChatHistoryGet without sending the request
     */
    async aiAdvisorChatHistoryGetRequestOpts(requestParameters: AiAdvisorChatHistoryGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['sessionId'] != null) {
            queryParameters['sessionId'] = requestParameters['sessionId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/ai/advisor/chat/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Retrieve AI Advisor Conversation History
     */
    async aiAdvisorChatHistoryGetRaw(requestParameters: AiAdvisorChatHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.aiAdvisorChatHistoryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * N/A
     * Retrieve AI Advisor Conversation History
     */
    async aiAdvisorChatHistoryGet(requestParameters: AiAdvisorChatHistoryGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.aiAdvisorChatHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
