/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SustainabilityInvestmentsImpactGet200Response,
} from '../models/index';
import {
    SustainabilityInvestmentsImpactGet200ResponseFromJSON,
    SustainabilityInvestmentsImpactGet200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class ImpactApi extends runtime.BaseAPI {

    /**
     * Creates request options for sustainabilityInvestmentsImpactGet without sending the request
     */
    async sustainabilityInvestmentsImpactGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sustainability/investments/impact`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Analyze ESG Impact of Investment Portfolio
     */
    async sustainabilityInvestmentsImpactGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SustainabilityInvestmentsImpactGet200Response>> {
        const requestOptions = await this.sustainabilityInvestmentsImpactGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SustainabilityInvestmentsImpactGet200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Analyze ESG Impact of Investment Portfolio
     */
    async sustainabilityInvestmentsImpactGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SustainabilityInvestmentsImpactGet200Response> {
        const response = await this.sustainabilityInvestmentsImpactGetRaw(initOverrides);
        return await response.value();
    }

}
