/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiLedgerAccountStatementsPost201Response,
  ApiLedgerAccountStatementsPostRequest,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiLedgerAccountStatementsPost201ResponseFromJSON,
    ApiLedgerAccountStatementsPost201ResponseToJSON,
    ApiLedgerAccountStatementsPostRequestFromJSON,
    ApiLedgerAccountStatementsPostRequestToJSON,
} from '../models/index';

export interface ApiLedgerAccountStatementsIdGetRequest {
    id: string;
}

export interface ApiLedgerAccountStatementsPostOperationRequest {
    idempotencyKey?: string;
    apiLedgerAccountStatementsPostRequest?: ApiLedgerAccountStatementsPostRequest;
}

/**
 * 
 */
export class LedgerAccountStatementApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiLedgerAccountStatementsIdGet without sending the request
     */
    async apiLedgerAccountStatementsIdGetRequestOpts(requestParameters: ApiLedgerAccountStatementsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiLedgerAccountStatementsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/ledger_account_statements/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * get ledger_account_statement
     */
    async apiLedgerAccountStatementsIdGetRaw(requestParameters: ApiLedgerAccountStatementsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiLedgerAccountStatementsPost201Response>> {
        const requestOptions = await this.apiLedgerAccountStatementsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiLedgerAccountStatementsPost201ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * get ledger_account_statement
     */
    async apiLedgerAccountStatementsIdGet(requestParameters: ApiLedgerAccountStatementsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiLedgerAccountStatementsPost201Response> {
        const response = await this.apiLedgerAccountStatementsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiLedgerAccountStatementsPost without sending the request
     */
    async apiLedgerAccountStatementsPostRequestOpts(requestParameters: ApiLedgerAccountStatementsPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/ledger_account_statements`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiLedgerAccountStatementsPostRequestToJSON(requestParameters['apiLedgerAccountStatementsPostRequest']),
        };
    }

    /**
     * N/A
     * create ledger_account_statement
     */
    async apiLedgerAccountStatementsPostRaw(requestParameters: ApiLedgerAccountStatementsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiLedgerAccountStatementsPost201Response>> {
        const requestOptions = await this.apiLedgerAccountStatementsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiLedgerAccountStatementsPost201ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * create ledger_account_statement
     */
    async apiLedgerAccountStatementsPost(requestParameters: ApiLedgerAccountStatementsPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiLedgerAccountStatementsPost201Response> {
        const response = await this.apiLedgerAccountStatementsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
