/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TransactionsTransactionIdCategorizePut200Response,
  TransactionsTransactionIdNotesPutRequest,
  UsersRegisterPost400Response,
} from '../models/index';
import {
    TransactionsTransactionIdCategorizePut200ResponseFromJSON,
    TransactionsTransactionIdCategorizePut200ResponseToJSON,
    TransactionsTransactionIdNotesPutRequestFromJSON,
    TransactionsTransactionIdNotesPutRequestToJSON,
    UsersRegisterPost400ResponseFromJSON,
    UsersRegisterPost400ResponseToJSON,
} from '../models/index';

export interface TransactionsTransactionIdNotesPutOperationRequest {
    transactionId: string;
    transactionsTransactionIdNotesPutRequest?: TransactionsTransactionIdNotesPutRequest;
}

/**
 * 
 */
export class NotesApi extends runtime.BaseAPI {

    /**
     * Creates request options for transactionsTransactionIdNotesPut without sending the request
     */
    async transactionsTransactionIdNotesPutRequestOpts(requestParameters: TransactionsTransactionIdNotesPutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling transactionsTransactionIdNotesPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/transactions/{transactionId}/notes`;
        urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionsTransactionIdNotesPutRequestToJSON(requestParameters['transactionsTransactionIdNotesPutRequest']),
        };
    }

    /**
     * N/A
     * Add/Update Notes for a Transaction
     */
    async transactionsTransactionIdNotesPutRaw(requestParameters: TransactionsTransactionIdNotesPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsTransactionIdCategorizePut200Response>> {
        const requestOptions = await this.transactionsTransactionIdNotesPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsTransactionIdCategorizePut200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Add/Update Notes for a Transaction
     */
    async transactionsTransactionIdNotesPut(requestParameters: TransactionsTransactionIdNotesPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsTransactionIdCategorizePut200Response> {
        const response = await this.transactionsTransactionIdNotesPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
