/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountsAccountIdOverdraftSettingsGet200Response,
  AccountsAccountIdOverdraftSettingsPutRequest,
  UsersRegisterPost400Response,
} from '../models/index';
import {
    AccountsAccountIdOverdraftSettingsGet200ResponseFromJSON,
    AccountsAccountIdOverdraftSettingsGet200ResponseToJSON,
    AccountsAccountIdOverdraftSettingsPutRequestFromJSON,
    AccountsAccountIdOverdraftSettingsPutRequestToJSON,
    UsersRegisterPost400ResponseFromJSON,
    UsersRegisterPost400ResponseToJSON,
} from '../models/index';

export interface AccountsAccountIdOverdraftSettingsGetRequest {
    accountId: string;
}

export interface AccountsAccountIdOverdraftSettingsPutOperationRequest {
    accountId: string;
    accountsAccountIdOverdraftSettingsPutRequest?: AccountsAccountIdOverdraftSettingsPutRequest;
}

/**
 * 
 */
export class OverdraftSettingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for accountsAccountIdOverdraftSettingsGet without sending the request
     */
    async accountsAccountIdOverdraftSettingsGetRequestOpts(requestParameters: AccountsAccountIdOverdraftSettingsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsAccountIdOverdraftSettingsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/accounts/{accountId}/overdraft-settings`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get Overdraft Protection Settings
     */
    async accountsAccountIdOverdraftSettingsGetRaw(requestParameters: AccountsAccountIdOverdraftSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountsAccountIdOverdraftSettingsGet200Response>> {
        const requestOptions = await this.accountsAccountIdOverdraftSettingsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountsAccountIdOverdraftSettingsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Get Overdraft Protection Settings
     */
    async accountsAccountIdOverdraftSettingsGet(requestParameters: AccountsAccountIdOverdraftSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountsAccountIdOverdraftSettingsGet200Response> {
        const response = await this.accountsAccountIdOverdraftSettingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for accountsAccountIdOverdraftSettingsPut without sending the request
     */
    async accountsAccountIdOverdraftSettingsPutRequestOpts(requestParameters: AccountsAccountIdOverdraftSettingsPutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsAccountIdOverdraftSettingsPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/accounts/{accountId}/overdraft-settings`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AccountsAccountIdOverdraftSettingsPutRequestToJSON(requestParameters['accountsAccountIdOverdraftSettingsPutRequest']),
        };
    }

    /**
     * N/A
     * Update Overdraft Protection Settings
     */
    async accountsAccountIdOverdraftSettingsPutRaw(requestParameters: AccountsAccountIdOverdraftSettingsPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountsAccountIdOverdraftSettingsGet200Response>> {
        const requestOptions = await this.accountsAccountIdOverdraftSettingsPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountsAccountIdOverdraftSettingsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Update Overdraft Protection Settings
     */
    async accountsAccountIdOverdraftSettingsPut(requestParameters: AccountsAccountIdOverdraftSettingsPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountsAccountIdOverdraftSettingsGet200Response> {
        const response = await this.accountsAccountIdOverdraftSettingsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
