/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiInvoicesPost200ResponsePaymentOrdersInner,
  ApiPaymentOrdersCreateAsyncPostRequest,
  ApiPaymentOrdersIdPatchRequest,
  ApiPaymentOrdersPostRequest,
  ApiSimulationsIncomingPaymentDetailsCreateAsyncPost202Response,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiInvoicesPost200ResponsePaymentOrdersInnerFromJSON,
    ApiInvoicesPost200ResponsePaymentOrdersInnerToJSON,
    ApiPaymentOrdersCreateAsyncPostRequestFromJSON,
    ApiPaymentOrdersCreateAsyncPostRequestToJSON,
    ApiPaymentOrdersIdPatchRequestFromJSON,
    ApiPaymentOrdersIdPatchRequestToJSON,
    ApiPaymentOrdersPostRequestFromJSON,
    ApiPaymentOrdersPostRequestToJSON,
    ApiSimulationsIncomingPaymentDetailsCreateAsyncPost202ResponseFromJSON,
    ApiSimulationsIncomingPaymentDetailsCreateAsyncPost202ResponseToJSON,
} from '../models/index';

export interface ApiInvoicesIdPaymentOrdersPaymentOrderIdPutRequest {
    id: string;
    paymentOrderId: string;
}

export interface ApiPaymentOrdersCreateAsyncPostOperationRequest {
    idempotencyKey?: string;
    apiPaymentOrdersCreateAsyncPostRequest?: ApiPaymentOrdersCreateAsyncPostRequest;
}

export interface ApiPaymentOrdersGetRequest {
    afterCursor?: string;
    perPage?: number;
    type?: ApiPaymentOrdersGetTypeEnum;
    priority?: ApiPaymentOrdersGetPriorityEnum;
    counterpartyId?: string;
    originatingAccountId?: string;
    transactionId?: string;
    status?: ApiPaymentOrdersGetStatusEnum;
    direction?: ApiPaymentOrdersGetDirectionEnum;
    referenceNumber?: string;
    effectiveDateStart?: Date;
    effectiveDateEnd?: Date;
    metadataKey0?: string;
}

export interface ApiPaymentOrdersIdGetRequest {
    id: string;
}

export interface ApiPaymentOrdersIdPatchOperationRequest {
    id: string;
    apiPaymentOrdersIdPatchRequest?: ApiPaymentOrdersIdPatchRequest;
}

export interface ApiPaymentOrdersPostOperationRequest {
    idempotencyKey?: string;
    apiPaymentOrdersPostRequest?: ApiPaymentOrdersPostRequest;
}

/**
 * 
 */
export class PaymentOrderApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiInvoicesIdPaymentOrdersPaymentOrderIdPut without sending the request
     */
    async apiInvoicesIdPaymentOrdersPaymentOrderIdPutRequestOpts(requestParameters: ApiInvoicesIdPaymentOrdersPaymentOrderIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiInvoicesIdPaymentOrdersPaymentOrderIdPut().'
            );
        }

        if (requestParameters['paymentOrderId'] == null) {
            throw new runtime.RequiredError(
                'paymentOrderId',
                'Required parameter "paymentOrderId" was null or undefined when calling apiInvoicesIdPaymentOrdersPaymentOrderIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/invoices/{id}/payment_orders/{payment_order_id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"payment_order_id"}}`, encodeURIComponent(String(requestParameters['paymentOrderId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * add payment_order_id to invoice
     */
    async apiInvoicesIdPaymentOrdersPaymentOrderIdPutRaw(requestParameters: ApiInvoicesIdPaymentOrdersPaymentOrderIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiInvoicesIdPaymentOrdersPaymentOrderIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * add payment_order_id to invoice
     */
    async apiInvoicesIdPaymentOrdersPaymentOrderIdPut(requestParameters: ApiInvoicesIdPaymentOrdersPaymentOrderIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiInvoicesIdPaymentOrdersPaymentOrderIdPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiPaymentOrdersCreateAsyncPost without sending the request
     */
    async apiPaymentOrdersCreateAsyncPostRequestOpts(requestParameters: ApiPaymentOrdersCreateAsyncPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/payment_orders/create_async`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiPaymentOrdersCreateAsyncPostRequestToJSON(requestParameters['apiPaymentOrdersCreateAsyncPostRequest']),
        };
    }

    /**
     * N/A
     * create async payment order
     */
    async apiPaymentOrdersCreateAsyncPostRaw(requestParameters: ApiPaymentOrdersCreateAsyncPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiSimulationsIncomingPaymentDetailsCreateAsyncPost202Response>> {
        const requestOptions = await this.apiPaymentOrdersCreateAsyncPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiSimulationsIncomingPaymentDetailsCreateAsyncPost202ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * create async payment order
     */
    async apiPaymentOrdersCreateAsyncPost(requestParameters: ApiPaymentOrdersCreateAsyncPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiSimulationsIncomingPaymentDetailsCreateAsyncPost202Response> {
        const response = await this.apiPaymentOrdersCreateAsyncPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPaymentOrdersGet without sending the request
     */
    async apiPaymentOrdersGetRequestOpts(requestParameters: ApiPaymentOrdersGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['priority'] != null) {
            queryParameters['priority'] = requestParameters['priority'];
        }

        if (requestParameters['counterpartyId'] != null) {
            queryParameters['counterparty_id'] = requestParameters['counterpartyId'];
        }

        if (requestParameters['originatingAccountId'] != null) {
            queryParameters['originating_account_id'] = requestParameters['originatingAccountId'];
        }

        if (requestParameters['transactionId'] != null) {
            queryParameters['transaction_id'] = requestParameters['transactionId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['referenceNumber'] != null) {
            queryParameters['reference_number'] = requestParameters['referenceNumber'];
        }

        if (requestParameters['effectiveDateStart'] != null) {
            queryParameters['effective_date_start'] = (requestParameters['effectiveDateStart'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['effectiveDateEnd'] != null) {
            queryParameters['effective_date_end'] = (requestParameters['effectiveDateEnd'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['metadataKey0'] != null) {
            queryParameters['metadata[key_0]'] = requestParameters['metadataKey0'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/payment_orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * list payment orders
     */
    async apiPaymentOrdersGetRaw(requestParameters: ApiPaymentOrdersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiInvoicesPost200ResponsePaymentOrdersInner>>> {
        const requestOptions = await this.apiPaymentOrdersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiInvoicesPost200ResponsePaymentOrdersInnerFromJSON));
    }

    /**
     * N/A
     * list payment orders
     */
    async apiPaymentOrdersGet(requestParameters: ApiPaymentOrdersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiInvoicesPost200ResponsePaymentOrdersInner>> {
        const response = await this.apiPaymentOrdersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPaymentOrdersIdGet without sending the request
     */
    async apiPaymentOrdersIdGetRequestOpts(requestParameters: ApiPaymentOrdersIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPaymentOrdersIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/payment_orders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * get payment order
     */
    async apiPaymentOrdersIdGetRaw(requestParameters: ApiPaymentOrdersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiInvoicesPost200ResponsePaymentOrdersInner>> {
        const requestOptions = await this.apiPaymentOrdersIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiInvoicesPost200ResponsePaymentOrdersInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * get payment order
     */
    async apiPaymentOrdersIdGet(requestParameters: ApiPaymentOrdersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiInvoicesPost200ResponsePaymentOrdersInner> {
        const response = await this.apiPaymentOrdersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPaymentOrdersIdPatch without sending the request
     */
    async apiPaymentOrdersIdPatchRequestOpts(requestParameters: ApiPaymentOrdersIdPatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPaymentOrdersIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/payment_orders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ApiPaymentOrdersIdPatchRequestToJSON(requestParameters['apiPaymentOrdersIdPatchRequest']),
        };
    }

    /**
     * N/A
     * update payment order
     */
    async apiPaymentOrdersIdPatchRaw(requestParameters: ApiPaymentOrdersIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiInvoicesPost200ResponsePaymentOrdersInner>> {
        const requestOptions = await this.apiPaymentOrdersIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiInvoicesPost200ResponsePaymentOrdersInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * update payment order
     */
    async apiPaymentOrdersIdPatch(requestParameters: ApiPaymentOrdersIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiInvoicesPost200ResponsePaymentOrdersInner> {
        const response = await this.apiPaymentOrdersIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPaymentOrdersPost without sending the request
     */
    async apiPaymentOrdersPostRequestOpts(requestParameters: ApiPaymentOrdersPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/payment_orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiPaymentOrdersPostRequestToJSON(requestParameters['apiPaymentOrdersPostRequest']),
        };
    }

    /**
     * N/A
     * create payment order
     */
    async apiPaymentOrdersPostRaw(requestParameters: ApiPaymentOrdersPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiInvoicesPost200ResponsePaymentOrdersInner>> {
        const requestOptions = await this.apiPaymentOrdersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiInvoicesPost200ResponsePaymentOrdersInnerFromJSON(jsonValue));
    }

    /**
     * N/A
     * create payment order
     */
    async apiPaymentOrdersPost(requestParameters: ApiPaymentOrdersPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiInvoicesPost200ResponsePaymentOrdersInner> {
        const response = await this.apiPaymentOrdersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiPaymentOrdersGetTypeEnum = {
    Ach: 'ach',
    AuBecs: 'au_becs',
    Bacs: 'bacs',
    Book: 'book',
    Card: 'card',
    Check: 'check',
    CrossBorder: 'cross_border',
    Eft: 'eft',
    Interac: 'interac',
    Masav: 'masav',
    Neft: 'neft',
    Nics: 'nics',
    Provxchange: 'provxchange',
    Rtp: 'rtp',
    SeBankgirot: 'se_bankgirot',
    Sen: 'sen',
    Sepa: 'sepa',
    Sic: 'sic',
    Signet: 'signet',
    Wire: 'wire',
    Zengin: 'zengin'
} as const;
export type ApiPaymentOrdersGetTypeEnum = typeof ApiPaymentOrdersGetTypeEnum[keyof typeof ApiPaymentOrdersGetTypeEnum];
/**
 * @export
 */
export const ApiPaymentOrdersGetPriorityEnum = {
    High: 'high',
    Normal: 'normal'
} as const;
export type ApiPaymentOrdersGetPriorityEnum = typeof ApiPaymentOrdersGetPriorityEnum[keyof typeof ApiPaymentOrdersGetPriorityEnum];
/**
 * @export
 */
export const ApiPaymentOrdersGetStatusEnum = {
    Approved: 'approved',
    Cancelled: 'cancelled',
    Completed: 'completed',
    Denied: 'denied',
    Failed: 'failed',
    NeedsApproval: 'needs_approval',
    Pending: 'pending',
    Processing: 'processing',
    Returned: 'returned',
    Reversed: 'reversed',
    Sent: 'sent'
} as const;
export type ApiPaymentOrdersGetStatusEnum = typeof ApiPaymentOrdersGetStatusEnum[keyof typeof ApiPaymentOrdersGetStatusEnum];
/**
 * @export
 */
export const ApiPaymentOrdersGetDirectionEnum = {
    Credit: 'credit',
    Debit: 'debit'
} as const;
export type ApiPaymentOrdersGetDirectionEnum = typeof ApiPaymentOrdersGetDirectionEnum[keyof typeof ApiPaymentOrdersGetDirectionEnum];
