/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaymentInitiationConsentCreatePost200Response,
  PaymentInitiationConsentGetPost200Response,
  PaymentInitiationConsentPaymentExecutePostDefaultResponse,
  SignalPreparePostDefaultResponse,
} from '../models/index';
import {
    PaymentInitiationConsentCreatePost200ResponseFromJSON,
    PaymentInitiationConsentCreatePost200ResponseToJSON,
    PaymentInitiationConsentGetPost200ResponseFromJSON,
    PaymentInitiationConsentGetPost200ResponseToJSON,
    PaymentInitiationConsentPaymentExecutePostDefaultResponseFromJSON,
    PaymentInitiationConsentPaymentExecutePostDefaultResponseToJSON,
    SignalPreparePostDefaultResponseFromJSON,
    SignalPreparePostDefaultResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class PaymentInitiationUKAndEuropeOnlyApi extends runtime.BaseAPI {

    /**
     * Creates request options for paymentInitiationConsentCreatePost without sending the request
     */
    async paymentInitiationConsentCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create Payment Consent
     */
    async paymentInitiationConsentCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentInitiationConsentCreatePost200Response>> {
        const requestOptions = await this.paymentInitiationConsentCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentInitiationConsentCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create Payment Consent
     */
    async paymentInitiationConsentCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentInitiationConsentCreatePost200Response> {
        const response = await this.paymentInitiationConsentCreatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentInitiationConsentGetPost without sending the request
     */
    async paymentInitiationConsentGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Payment Consent
     */
    async paymentInitiationConsentGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentInitiationConsentGetPost200Response>> {
        const requestOptions = await this.paymentInitiationConsentGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentInitiationConsentGetPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Get Payment Consent
     */
    async paymentInitiationConsentGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentInitiationConsentGetPost200Response> {
        const response = await this.paymentInitiationConsentGetPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentInitiationConsentPaymentExecutePost without sending the request
     */
    async paymentInitiationConsentPaymentExecutePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/payment/execute`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Execute Consent Based Payment
     */
    async paymentInitiationConsentPaymentExecutePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentInitiationConsentPaymentExecutePostDefaultResponse>> {
        const requestOptions = await this.paymentInitiationConsentPaymentExecutePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentInitiationConsentPaymentExecutePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Execute Consent Based Payment
     */
    async paymentInitiationConsentPaymentExecutePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentInitiationConsentPaymentExecutePostDefaultResponse> {
        const response = await this.paymentInitiationConsentPaymentExecutePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentInitiationConsentRevokePost without sending the request
     */
    async paymentInitiationConsentRevokePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/revoke`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke Payment Consent
     */
    async paymentInitiationConsentRevokePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.paymentInitiationConsentRevokePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Revoke Payment Consent
     */
    async paymentInitiationConsentRevokePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.paymentInitiationConsentRevokePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentInitiationPaymentCreatePost without sending the request
     */
    async paymentInitiationPaymentCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/payment/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Create Payment
     */
    async paymentInitiationPaymentCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.paymentInitiationPaymentCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * Create Payment
     */
    async paymentInitiationPaymentCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentInitiationPaymentCreatePostRaw(initOverrides);
    }

    /**
     * Creates request options for paymentInitiationPaymentGetPost without sending the request
     */
    async paymentInitiationPaymentGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/payment/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get Payment
     */
    async paymentInitiationPaymentGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.paymentInitiationPaymentGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * Get Payment
     */
    async paymentInitiationPaymentGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentInitiationPaymentGetPostRaw(initOverrides);
    }

    /**
     * Creates request options for paymentInitiationPaymentListPost without sending the request
     */
    async paymentInitiationPaymentListPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/payment/list`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * List Payments
     */
    async paymentInitiationPaymentListPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.paymentInitiationPaymentListPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * List Payments
     */
    async paymentInitiationPaymentListPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentInitiationPaymentListPostRaw(initOverrides);
    }

    /**
     * Creates request options for paymentInitiationRecipientCreatePost without sending the request
     */
    async paymentInitiationRecipientCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/recipient/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Create Payment Recipient
     */
    async paymentInitiationRecipientCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.paymentInitiationRecipientCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * Create Payment Recipient
     */
    async paymentInitiationRecipientCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentInitiationRecipientCreatePostRaw(initOverrides);
    }

    /**
     * Creates request options for paymentInitiationRecipientGetPost without sending the request
     */
    async paymentInitiationRecipientGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/recipient/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get Payment Recipient
     */
    async paymentInitiationRecipientGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.paymentInitiationRecipientGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * Get Payment Recipient
     */
    async paymentInitiationRecipientGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentInitiationRecipientGetPostRaw(initOverrides);
    }

    /**
     * Creates request options for paymentInitiationRecipientListPost without sending the request
     */
    async paymentInitiationRecipientListPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/recipient/list`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * List Payment Recipients
     */
    async paymentInitiationRecipientListPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.paymentInitiationRecipientListPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * List Payment Recipients
     */
    async paymentInitiationRecipientListPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentInitiationRecipientListPostRaw(initOverrides);
    }

    /**
     * Creates request options for sandboxPaymentSimulatePost without sending the request
     */
    async sandboxPaymentSimulatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sandbox/payment/simulate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * (Sandbox) Simulate Payment activity
     */
    async sandboxPaymentSimulatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.sandboxPaymentSimulatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * N/A
     * (Sandbox) Simulate Payment activity
     */
    async sandboxPaymentSimulatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sandboxPaymentSimulatePostRaw(initOverrides);
    }

}
