/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SignalPreparePostDefaultResponse,
  TransferRefundCreatePost200Response,
} from '../models/index';
import {
    SignalPreparePostDefaultResponseFromJSON,
    SignalPreparePostDefaultResponseToJSON,
    TransferRefundCreatePost200ResponseFromJSON,
    TransferRefundCreatePost200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class RefundsApi extends runtime.BaseAPI {

    /**
     * Creates request options for sandboxTransferRefundSimulatePost without sending the request
     */
    async sandboxTransferRefundSimulatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sandbox/transfer/refund/simulate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * (Sandbox) Simulate a refund event
     */
    async sandboxTransferRefundSimulatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.sandboxTransferRefundSimulatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * (Sandbox) Simulate a refund event
     */
    async sandboxTransferRefundSimulatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.sandboxTransferRefundSimulatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transferRefundCancelPost without sending the request
     */
    async transferRefundCancelPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/transfer/refund/cancel`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Cancel a refund
     */
    async transferRefundCancelPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.transferRefundCancelPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Cancel a refund
     */
    async transferRefundCancelPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.transferRefundCancelPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transferRefundCreatePost without sending the request
     */
    async transferRefundCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/transfer/refund/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create a refund
     */
    async transferRefundCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferRefundCreatePost200Response>> {
        const requestOptions = await this.transferRefundCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferRefundCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a refund
     */
    async transferRefundCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferRefundCreatePost200Response> {
        const response = await this.transferRefundCreatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transferRefundGetPost without sending the request
     */
    async transferRefundGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/transfer/refund/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get a refund
     */
    async transferRefundGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferRefundCreatePost200Response>> {
        const requestOptions = await this.transferRefundGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferRefundCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Get a refund
     */
    async transferRefundGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferRefundCreatePost200Response> {
        const response = await this.transferRefundGetPostRaw(initOverrides);
        return await response.value();
    }

}
