/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SandboxTransferTestClockCreatePost200Response,
  SandboxTransferTestClockListPost200Response,
  SignalPreparePostDefaultResponse,
} from '../models/index';
import {
    SandboxTransferTestClockCreatePost200ResponseFromJSON,
    SandboxTransferTestClockCreatePost200ResponseToJSON,
    SandboxTransferTestClockListPost200ResponseFromJSON,
    SandboxTransferTestClockListPost200ResponseToJSON,
    SignalPreparePostDefaultResponseFromJSON,
    SignalPreparePostDefaultResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class SandboxSimulateThePassageOfTimeApi extends runtime.BaseAPI {

    /**
     * Creates request options for sandboxTransferTestClockAdvancePost without sending the request
     */
    async sandboxTransferTestClockAdvancePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sandbox/transfer/test_clock/advance`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Advance a test clock
     */
    async sandboxTransferTestClockAdvancePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.sandboxTransferTestClockAdvancePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Advance a test clock
     */
    async sandboxTransferTestClockAdvancePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.sandboxTransferTestClockAdvancePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sandboxTransferTestClockCreatePost without sending the request
     */
    async sandboxTransferTestClockCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sandbox/transfer/test_clock/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Create a test clock
     */
    async sandboxTransferTestClockCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxTransferTestClockCreatePost200Response>> {
        const requestOptions = await this.sandboxTransferTestClockCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxTransferTestClockCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Create a test clock
     */
    async sandboxTransferTestClockCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxTransferTestClockCreatePost200Response> {
        const response = await this.sandboxTransferTestClockCreatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sandboxTransferTestClockGetPost without sending the request
     */
    async sandboxTransferTestClockGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sandbox/transfer/test_clock/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get a test clock
     */
    async sandboxTransferTestClockGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxTransferTestClockCreatePost200Response>> {
        const requestOptions = await this.sandboxTransferTestClockGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxTransferTestClockCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Get a test clock
     */
    async sandboxTransferTestClockGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxTransferTestClockCreatePost200Response> {
        const response = await this.sandboxTransferTestClockGetPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sandboxTransferTestClockListPost without sending the request
     */
    async sandboxTransferTestClockListPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sandbox/transfer/test_clock/list`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * List test clocks
     */
    async sandboxTransferTestClockListPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxTransferTestClockListPost200Response>> {
        const requestOptions = await this.sandboxTransferTestClockListPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxTransferTestClockListPost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * List test clocks
     */
    async sandboxTransferTestClockListPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxTransferTestClockListPost200Response> {
        const response = await this.sandboxTransferTestClockListPostRaw(initOverrides);
        return await response.value();
    }

}
