/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SignalDecisionReportPostRequest,
  SignalEvaluatePostRequest,
  SignalPreparePostDefaultResponse,
  SignalPreparePostRequest,
  SignalReturnReportPostRequest,
} from '../models/index';
import {
    SignalDecisionReportPostRequestFromJSON,
    SignalDecisionReportPostRequestToJSON,
    SignalEvaluatePostRequestFromJSON,
    SignalEvaluatePostRequestToJSON,
    SignalPreparePostDefaultResponseFromJSON,
    SignalPreparePostDefaultResponseToJSON,
    SignalPreparePostRequestFromJSON,
    SignalPreparePostRequestToJSON,
    SignalReturnReportPostRequestFromJSON,
    SignalReturnReportPostRequestToJSON,
} from '../models/index';

export interface SignalDecisionReportPostOperationRequest {
    signalDecisionReportPostRequest?: SignalDecisionReportPostRequest;
}

export interface SignalEvaluatePostOperationRequest {
    signalEvaluatePostRequest?: SignalEvaluatePostRequest;
}

export interface SignalPreparePostOperationRequest {
    signalPreparePostRequest?: SignalPreparePostRequest;
}

export interface SignalReturnReportPostOperationRequest {
    signalReturnReportPostRequest?: SignalReturnReportPostRequest;
}

/**
 * 
 */
export class SignalBalanceAndSignalTransactionScoresApi extends runtime.BaseAPI {

    /**
     * Creates request options for signalDecisionReportPost without sending the request
     */
    async signalDecisionReportPostRequestOpts(requestParameters: SignalDecisionReportPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/signal/decision/report`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignalDecisionReportPostRequestToJSON(requestParameters['signalDecisionReportPostRequest']),
        };
    }

    /**
     * Report whether you initiated an ACH transaction
     */
    async signalDecisionReportPostRaw(requestParameters: SignalDecisionReportPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.signalDecisionReportPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Report whether you initiated an ACH transaction
     */
    async signalDecisionReportPost(requestParameters: SignalDecisionReportPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.signalDecisionReportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for signalEvaluatePost without sending the request
     */
    async signalEvaluatePostRequestOpts(requestParameters: SignalEvaluatePostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/signal/evaluate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignalEvaluatePostRequestToJSON(requestParameters['signalEvaluatePostRequest']),
        };
    }

    /**
     * Evaluate a planned ACH transaction
     */
    async signalEvaluatePostRaw(requestParameters: SignalEvaluatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.signalEvaluatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Evaluate a planned ACH transaction
     */
    async signalEvaluatePost(requestParameters: SignalEvaluatePostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signalEvaluatePostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for signalPreparePost without sending the request
     */
    async signalPreparePostRequestOpts(requestParameters: SignalPreparePostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/signal/prepare`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignalPreparePostRequestToJSON(requestParameters['signalPreparePostRequest']),
        };
    }

    /**
     * (Optional) Initialize an existing Auth Item with Signal Transaction Scores
     */
    async signalPreparePostRaw(requestParameters: SignalPreparePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.signalPreparePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * (Optional) Initialize an existing Auth Item with Signal Transaction Scores
     */
    async signalPreparePost(requestParameters: SignalPreparePostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.signalPreparePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for signalReturnReportPost without sending the request
     */
    async signalReturnReportPostRequestOpts(requestParameters: SignalReturnReportPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/signal/return/report`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignalReturnReportPostRequestToJSON(requestParameters['signalReturnReportPostRequest']),
        };
    }

    /**
     * Report an ACH return
     */
    async signalReturnReportPostRaw(requestParameters: SignalReturnReportPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.signalReturnReportPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Report an ACH return
     */
    async signalReturnReportPost(requestParameters: SignalReturnReportPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.signalReturnReportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
