/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface CorporateAnomaliesAnomalyIdStatusPutRequest {
    anomalyId: string;
    body?: object;
}

export interface PaymentsInternationalPaymentIdStatusGetRequest {
    paymentId: string;
}

/**
 * 
 */
export class StatusApi extends runtime.BaseAPI {

    /**
     * Creates request options for corporateAnomaliesAnomalyIdStatusPut without sending the request
     */
    async corporateAnomaliesAnomalyIdStatusPutRequestOpts(requestParameters: CorporateAnomaliesAnomalyIdStatusPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['anomalyId'] == null) {
            throw new runtime.RequiredError(
                'anomalyId',
                'Required parameter "anomalyId" was null or undefined when calling corporateAnomaliesAnomalyIdStatusPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/corporate/anomalies/{anomalyId}/status`;
        urlPath = urlPath.replace(`{${"anomalyId"}}`, encodeURIComponent(String(requestParameters['anomalyId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * N/A
     * Update Anomaly Review Status
     */
    async corporateAnomaliesAnomalyIdStatusPutRaw(requestParameters: CorporateAnomaliesAnomalyIdStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.corporateAnomaliesAnomalyIdStatusPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * N/A
     * Update Anomaly Review Status
     */
    async corporateAnomaliesAnomalyIdStatusPut(requestParameters: CorporateAnomaliesAnomalyIdStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.corporateAnomaliesAnomalyIdStatusPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentsInternationalPaymentIdStatusGet without sending the request
     */
    async paymentsInternationalPaymentIdStatusGetRequestOpts(requestParameters: PaymentsInternationalPaymentIdStatusGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling paymentsInternationalPaymentIdStatusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payments/international/{paymentId}/status`;
        urlPath = urlPath.replace(`{${"paymentId"}}`, encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get Status of an International Payment
     */
    async paymentsInternationalPaymentIdStatusGetRaw(requestParameters: PaymentsInternationalPaymentIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.paymentsInternationalPaymentIdStatusGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * N/A
     * Get Status of an International Payment
     */
    async paymentsInternationalPaymentIdStatusGet(requestParameters: PaymentsInternationalPaymentIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.paymentsInternationalPaymentIdStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
