/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAccountsTypeAccountIdAccountDetailsPost404Response,
  ApiTransactionsTransactionIdLineItemsGet200ResponseInner,
} from '../models/index';
import {
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsPost404ResponseToJSON,
    ApiTransactionsTransactionIdLineItemsGet200ResponseInnerFromJSON,
    ApiTransactionsTransactionIdLineItemsGet200ResponseInnerToJSON,
} from '../models/index';

export interface ApiTransactionLineItemsGetRequest {
    afterCursor?: string;
    idKey0?: string;
    type?: ApiTransactionLineItemsGetTypeEnum;
    perPage?: number;
    transactionId?: string;
}

export interface ApiTransactionLineItemsIdGetRequest {
    id: string;
}

export interface ApiTransactionsTransactionIdLineItemsGetRequest {
    transactionId: string;
    afterCursor?: string;
    type?: ApiTransactionsTransactionIdLineItemsGetTypeEnum;
    perPage?: number;
}

/**
 * 
 */
export class TransactionLineItemApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiTransactionLineItemsGet without sending the request
     */
    async apiTransactionLineItemsGetRequestOpts(requestParameters: ApiTransactionLineItemsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['idKey0'] != null) {
            queryParameters['id[key_0]'] = requestParameters['idKey0'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['transactionId'] != null) {
            queryParameters['transaction_id'] = requestParameters['transactionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/transaction_line_items`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list transaction_line_items
     */
    async apiTransactionLineItemsGetRaw(requestParameters: ApiTransactionLineItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiTransactionsTransactionIdLineItemsGet200ResponseInner>>> {
        const requestOptions = await this.apiTransactionLineItemsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiTransactionsTransactionIdLineItemsGet200ResponseInnerFromJSON));
    }

    /**
     * list transaction_line_items
     */
    async apiTransactionLineItemsGet(requestParameters: ApiTransactionLineItemsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiTransactionsTransactionIdLineItemsGet200ResponseInner>> {
        const response = await this.apiTransactionLineItemsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTransactionLineItemsIdGet without sending the request
     */
    async apiTransactionLineItemsIdGetRequestOpts(requestParameters: ApiTransactionLineItemsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTransactionLineItemsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/transaction_line_items/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get transaction line item
     */
    async apiTransactionLineItemsIdGetRaw(requestParameters: ApiTransactionLineItemsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiTransactionsTransactionIdLineItemsGet200ResponseInner>> {
        const requestOptions = await this.apiTransactionLineItemsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiTransactionsTransactionIdLineItemsGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * get transaction line item
     */
    async apiTransactionLineItemsIdGet(requestParameters: ApiTransactionLineItemsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiTransactionsTransactionIdLineItemsGet200ResponseInner> {
        const response = await this.apiTransactionLineItemsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTransactionsTransactionIdLineItemsGet without sending the request
     */
    async apiTransactionsTransactionIdLineItemsGetRequestOpts(requestParameters: ApiTransactionsTransactionIdLineItemsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling apiTransactionsTransactionIdLineItemsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['afterCursor'] != null) {
            queryParameters['after_cursor'] = requestParameters['afterCursor'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/transactions/{transaction_id}/line_items`;
        urlPath = urlPath.replace(`{${"transaction_id"}}`, encodeURIComponent(String(requestParameters['transactionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * list transaction_line_items
     */
    async apiTransactionsTransactionIdLineItemsGetRaw(requestParameters: ApiTransactionsTransactionIdLineItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiTransactionsTransactionIdLineItemsGet200ResponseInner>>> {
        const requestOptions = await this.apiTransactionsTransactionIdLineItemsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiTransactionsTransactionIdLineItemsGet200ResponseInnerFromJSON));
    }

    /**
     * N/A
     * list transaction_line_items
     */
    async apiTransactionsTransactionIdLineItemsGet(requestParameters: ApiTransactionsTransactionIdLineItemsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiTransactionsTransactionIdLineItemsGet200ResponseInner>> {
        const response = await this.apiTransactionsTransactionIdLineItemsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiTransactionLineItemsGetTypeEnum = {
    Originating: 'originating',
    Receiving: 'receiving'
} as const;
export type ApiTransactionLineItemsGetTypeEnum = typeof ApiTransactionLineItemsGetTypeEnum[keyof typeof ApiTransactionLineItemsGetTypeEnum];
/**
 * @export
 */
export const ApiTransactionsTransactionIdLineItemsGetTypeEnum = {
    Originating: 'originating',
    Receiving: 'receiving'
} as const;
export type ApiTransactionsTransactionIdLineItemsGetTypeEnum = typeof ApiTransactionsTransactionIdLineItemsGetTypeEnum[keyof typeof ApiTransactionsTransactionIdLineItemsGetTypeEnum];
