/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TransferConfigurationGetPost200Response,
  TransferMetricsGetPost200Response,
} from '../models/index';
import {
    TransferConfigurationGetPost200ResponseFromJSON,
    TransferConfigurationGetPost200ResponseToJSON,
    TransferMetricsGetPost200ResponseFromJSON,
    TransferMetricsGetPost200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TransferMetricsAndLimitsApi extends runtime.BaseAPI {

    /**
     * Creates request options for transferConfigurationGetPost without sending the request
     */
    async transferConfigurationGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/transfer/configuration/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get Transfer configuration and limits
     */
    async transferConfigurationGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferConfigurationGetPost200Response>> {
        const requestOptions = await this.transferConfigurationGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferConfigurationGetPost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Get Transfer configuration and limits
     */
    async transferConfigurationGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferConfigurationGetPost200Response> {
        const response = await this.transferConfigurationGetPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transferMetricsGetPost without sending the request
     */
    async transferMetricsGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/transfer/metrics/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * N/A
     * Get Transfer Metrics
     */
    async transferMetricsGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferMetricsGetPost200Response>> {
        const requestOptions = await this.transferMetricsGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferMetricsGetPost200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Get Transfer Metrics
     */
    async transferMetricsGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferMetricsGetPost200Response> {
        const response = await this.transferMetricsGetPostRaw(initOverrides);
        return await response.value();
    }

}
