/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaymentInitiationConsentCreatePost200Response,
  PaymentInitiationConsentGetPost200Response,
  PaymentInitiationConsentPaymentExecutePostDefaultResponse,
  SignalPreparePostDefaultResponse,
} from '../models/index';
import {
    PaymentInitiationConsentCreatePost200ResponseFromJSON,
    PaymentInitiationConsentCreatePost200ResponseToJSON,
    PaymentInitiationConsentGetPost200ResponseFromJSON,
    PaymentInitiationConsentGetPost200ResponseToJSON,
    PaymentInitiationConsentPaymentExecutePostDefaultResponseFromJSON,
    PaymentInitiationConsentPaymentExecutePostDefaultResponseToJSON,
    SignalPreparePostDefaultResponseFromJSON,
    SignalPreparePostDefaultResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class VariableRecurringPaymentsUKOnlyApi extends runtime.BaseAPI {

    /**
     * Creates request options for paymentInitiationConsentCreatePost without sending the request
     */
    async paymentInitiationConsentCreatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create Payment Consent
     */
    async paymentInitiationConsentCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentInitiationConsentCreatePost200Response>> {
        const requestOptions = await this.paymentInitiationConsentCreatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentInitiationConsentCreatePost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create Payment Consent
     */
    async paymentInitiationConsentCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentInitiationConsentCreatePost200Response> {
        const response = await this.paymentInitiationConsentCreatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentInitiationConsentGetPost without sending the request
     */
    async paymentInitiationConsentGetPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Payment Consent
     */
    async paymentInitiationConsentGetPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentInitiationConsentGetPost200Response>> {
        const requestOptions = await this.paymentInitiationConsentGetPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentInitiationConsentGetPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Get Payment Consent
     */
    async paymentInitiationConsentGetPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentInitiationConsentGetPost200Response> {
        const response = await this.paymentInitiationConsentGetPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentInitiationConsentPaymentExecutePost without sending the request
     */
    async paymentInitiationConsentPaymentExecutePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/payment/execute`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Execute Consent Based Payment
     */
    async paymentInitiationConsentPaymentExecutePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentInitiationConsentPaymentExecutePostDefaultResponse>> {
        const requestOptions = await this.paymentInitiationConsentPaymentExecutePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentInitiationConsentPaymentExecutePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Execute Consent Based Payment
     */
    async paymentInitiationConsentPaymentExecutePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentInitiationConsentPaymentExecutePostDefaultResponse> {
        const response = await this.paymentInitiationConsentPaymentExecutePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentInitiationConsentRevokePost without sending the request
     */
    async paymentInitiationConsentRevokePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/payment_initiation/consent/revoke`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke Payment Consent
     */
    async paymentInitiationConsentRevokePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignalPreparePostDefaultResponse>> {
        const requestOptions = await this.paymentInitiationConsentRevokePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignalPreparePostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Revoke Payment Consent
     */
    async paymentInitiationConsentRevokePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignalPreparePostDefaultResponse> {
        const response = await this.paymentInitiationConsentRevokePostRaw(initOverrides);
        return await response.value();
    }

}
