/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CorporateCardsCardIdControlsPut200Response,
  CorporateCardsVirtualPostRequest,
} from '../models/index';
import {
    CorporateCardsCardIdControlsPut200ResponseFromJSON,
    CorporateCardsCardIdControlsPut200ResponseToJSON,
    CorporateCardsVirtualPostRequestFromJSON,
    CorporateCardsVirtualPostRequestToJSON,
} from '../models/index';

export interface CorporateCardsVirtualPostOperationRequest {
    corporateCardsVirtualPostRequest?: CorporateCardsVirtualPostRequest;
}

/**
 * 
 */
export class VirtualApi extends runtime.BaseAPI {

    /**
     * Creates request options for corporateCardsVirtualPost without sending the request
     */
    async corporateCardsVirtualPostRequestOpts(requestParameters: CorporateCardsVirtualPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/corporate/cards/virtual`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CorporateCardsVirtualPostRequestToJSON(requestParameters['corporateCardsVirtualPostRequest']),
        };
    }

    /**
     * N/A
     * Issue a New Virtual Corporate Card
     */
    async corporateCardsVirtualPostRaw(requestParameters: CorporateCardsVirtualPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorporateCardsCardIdControlsPut200Response>> {
        const requestOptions = await this.corporateCardsVirtualPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorporateCardsCardIdControlsPut200ResponseFromJSON(jsonValue));
    }

    /**
     * N/A
     * Issue a New Virtual Corporate Card
     */
    async corporateCardsVirtualPost(requestParameters: CorporateCardsVirtualPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorporateCardsCardIdControlsPut200Response> {
        const response = await this.corporateCardsVirtualPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
