/* tslint:disable */
/* eslint-disable */
/**
 * Token Authorization
 * Exchanging the authorization code for an access/refresh token in order to grant a data aggregator permission to access a user’s data and share it with a fintech app. The revoke endpoint allows an aggregator to revoke access for a fintech app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTokenResponse
 */
export interface AccessTokenResponse {
    /**
     * Type of the access token issued.  This is bearer token for authorization_code grant type
     * @type {string}
     * @memberof AccessTokenResponse
     */
    tokenType: string;
    /**
     * The access token value received after exchanging the authorization token. This field should be passed as Authorization header in API request calls
     * @type {string}
     * @memberof AccessTokenResponse
     */
    accessToken: string;
    /**
     * Validity of access token in seconds
     * @type {number}
     * @memberof AccessTokenResponse
     */
    expiresIn: number;
    /**
     * Set of scopes allowed by customer and separated by space
     * @type {string}
     * @memberof AccessTokenResponse
     */
    scope: string;
    /**
     * You can use this token to refresh an expired access_token.
     * @type {string}
     * @memberof AccessTokenResponse
     */
    refreshToken: string;
    /**
     * Validity of refresh token in seconds
     * @type {number}
     * @memberof AccessTokenResponse
     */
    refreshTokenExpiresIn: number;
}

/**
 * Check if a given object implements the AccessTokenResponse interface.
 */
export function instanceOfAccessTokenResponse(value: object): value is AccessTokenResponse {
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('refreshTokenExpiresIn' in value) || value['refreshTokenExpiresIn'] === undefined) return false;
    return true;
}

export function AccessTokenResponseFromJSON(json: any): AccessTokenResponse {
    return AccessTokenResponseFromJSONTyped(json, false);
}

export function AccessTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenType': json['token_type'],
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'],
        'scope': json['scope'],
        'refreshToken': json['refresh_token'],
        'refreshTokenExpiresIn': json['refresh_token_expires_in'],
    };
}

export function AccessTokenResponseToJSON(json: any): AccessTokenResponse {
    return AccessTokenResponseToJSONTyped(json, false);
}

export function AccessTokenResponseToJSONTyped(value?: AccessTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token_type': value['tokenType'],
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'scope': value['scope'],
        'refresh_token': value['refreshToken'],
        'refresh_token_expires_in': value['refreshTokenExpiresIn'],
    };
}
