/* tslint:disable */
/* eslint-disable */
/**
 * Dynamic Client Registration Authorization
 * APIs will be used by Citi Partners to authenticate and generate OAuth Access Token to consume protected apis used for app registration, update, retrieve and revoke the same
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientAuthenRequest
 */
export interface ClientAuthenRequest {
    /**
     * Name of the OAuth Grant Type requested
     * @type {string}
     * @memberof ClientAuthenRequest
     */
    grantType: string;
    /**
     * Scope binded to the OAuth Access Token generated by IDP
     * @type {string}
     * @memberof ClientAuthenRequest
     */
    scope: string;
}

/**
 * Check if a given object implements the ClientAuthenRequest interface.
 */
export function instanceOfClientAuthenRequest(value: object): value is ClientAuthenRequest {
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function ClientAuthenRequestFromJSON(json: any): ClientAuthenRequest {
    return ClientAuthenRequestFromJSONTyped(json, false);
}

export function ClientAuthenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAuthenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'grantType': json['grant_type'],
        'scope': json['scope'],
    };
}

export function ClientAuthenRequestToJSON(json: any): ClientAuthenRequest {
    return ClientAuthenRequestToJSONTyped(json, false);
}

export function ClientAuthenRequestToJSONTyped(value?: ClientAuthenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grant_type': value['grantType'],
        'scope': value['scope'],
    };
}
