/* tslint:disable */
/* eslint-disable */
/**
 * Products_Partner_View
 * Returns a list of all active products held by a Citi customer. PCF Deployment Reference name --> AM-V-Products
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface Products
 */
export interface Products {
    /**
     * Unqiue Id for a customer
     * @type {string}
     * @memberof Products
     */
    customerId: string;
    /**
     * List of all products a Citi customer with account group such as credit card, checking and so on
     * @type {Array<Product>}
     * @memberof Products
     */
    products?: Array<Product>;
}

/**
 * Check if a given object implements the Products interface.
 */
export function instanceOfProducts(value: object): value is Products {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    return true;
}

export function ProductsFromJSON(json: any): Products {
    return ProductsFromJSONTyped(json, false);
}

export function ProductsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Products {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customerId'],
        'products': json['products'] == null ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
    };
}

export function ProductsToJSON(json: any): Products {
    return ProductsToJSONTyped(json, false);
}

export function ProductsToJSONTyped(value?: Products | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customerId': value['customerId'],
        'products': value['products'] == null ? undefined : ((value['products'] as Array<any>).map(ProductToJSON)),
    };
}
