/* tslint:disable */
/* eslint-disable */
/**
 * Products_Partner_View
 * Returns a list of all active products held by a Citi customer. PCF Deployment Reference name --> AM-V-Products
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * Long-term persistent identity of the account. Not an account number.
     * @type {string}
     * @memberof Product
     */
    accountId: string;
    /**
     * The status of the account. Currently this API returns ACTIVE products only.
     * @type {string}
     * @memberof Product
     */
    status: ProductStatusEnum;
    /**
     * Citi’s product name.
     * @type {string}
     * @memberof Product
     */
    productName: string;
    /**
     * Account Type is a classification of accounts according to their common characteristics
     * @type {string}
     * @memberof Product
     */
    accountType: ProductAccountTypeEnum;
    /**
     * A masked account number that can be displayed to the end customer to identify the account. Note - It displays only the last 4 digits of the account number, with the remaining numbers masked as "X".
     * @type {string}
     * @memberof Product
     */
    accountNumberDisplay: string;
}


/**
 * @export
 */
export const ProductStatusEnum = {
    Active: 'ACTIVE'
} as const;
export type ProductStatusEnum = typeof ProductStatusEnum[keyof typeof ProductStatusEnum];

/**
 * @export
 */
export const ProductAccountTypeEnum = {
    Checking: 'CHECKING',
    Savings: 'SAVINGS',
    CreditCard: 'CREDIT_CARD'
} as const;
export type ProductAccountTypeEnum = typeof ProductAccountTypeEnum[keyof typeof ProductAccountTypeEnum];


/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('accountNumberDisplay' in value) || value['accountNumberDisplay'] === undefined) return false;
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'status': json['status'],
        'productName': json['productName'],
        'accountType': json['accountType'],
        'accountNumberDisplay': json['accountNumberDisplay'],
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Product | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'status': value['status'],
        'productName': value['productName'],
        'accountType': value['accountType'],
        'accountNumberDisplay': value['accountNumberDisplay'],
    };
}
