/* tslint:disable */
/* eslint-disable */
/**
 * Token Authorization
 * Exchanging the authorization code for an access/refresh token in order to grant a data aggregator permission to access a user’s data and share it with a fintech app. The revoke endpoint allows an aggregator to revoke access for a fintech app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * The grant type. Valid value is refresh_token.
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    grantType: string;
    /**
     * The refresh token issued to the client
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenRequest interface.
 */
export function instanceOfRefreshTokenRequest(value: object): value is RefreshTokenRequest {
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshTokenRequestFromJSON(json: any): RefreshTokenRequest {
    return RefreshTokenRequestFromJSONTyped(json, false);
}

export function RefreshTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'grantType': json['grant_type'],
        'refreshToken': json['refresh_token'],
    };
}

export function RefreshTokenRequestToJSON(json: any): RefreshTokenRequest {
    return RefreshTokenRequestToJSONTyped(json, false);
}

export function RefreshTokenRequestToJSONTyped(value?: RefreshTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grant_type': value['grantType'],
        'refresh_token': value['refreshToken'],
    };
}
