/* tslint:disable */
/* eslint-disable */
/**
 * Accounts_AccountTransactions_FinancialDetails_Digital_Domain_OpenAPI
 * This MS will provide account summary and transaction list for a member/customer.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountSummary } from './AccountSummary';
import {
    AccountSummaryFromJSON,
    AccountSummaryFromJSONTyped,
    AccountSummaryToJSON,
    AccountSummaryToJSONTyped,
} from './AccountSummary';

/**
 * 
 * @export
 * @interface RetrieveAccountSummaryResponse
 */
export interface RetrieveAccountSummaryResponse {
    /**
     * 
     * @type {Array<AccountSummary>}
     * @memberof RetrieveAccountSummaryResponse
     */
    accountSummary?: Array<AccountSummary>;
}

/**
 * Check if a given object implements the RetrieveAccountSummaryResponse interface.
 */
export function instanceOfRetrieveAccountSummaryResponse(value: object): value is RetrieveAccountSummaryResponse {
    return true;
}

export function RetrieveAccountSummaryResponseFromJSON(json: any): RetrieveAccountSummaryResponse {
    return RetrieveAccountSummaryResponseFromJSONTyped(json, false);
}

export function RetrieveAccountSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveAccountSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountSummary': json['accountSummary'] == null ? undefined : ((json['accountSummary'] as Array<any>).map(AccountSummaryFromJSON)),
    };
}

export function RetrieveAccountSummaryResponseToJSON(json: any): RetrieveAccountSummaryResponse {
    return RetrieveAccountSummaryResponseToJSONTyped(json, false);
}

export function RetrieveAccountSummaryResponseToJSONTyped(value?: RetrieveAccountSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountSummary': value['accountSummary'] == null ? undefined : ((value['accountSummary'] as Array<any>).map(AccountSummaryToJSON)),
    };
}
