/* tslint:disable */
/* eslint-disable */
/**
 * Token Authorization
 * Exchanging the authorization code for an access/refresh token in order to grant a data aggregator permission to access a user’s data and share it with a fintech app. The revoke endpoint allows an aggregator to revoke access for a fintech app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeTokenResponse
 */
export interface RevokeTokenResponse {
    /**
     * The status of the token revocation request.
     * @type {string}
     * @memberof RevokeTokenResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the RevokeTokenResponse interface.
 */
export function instanceOfRevokeTokenResponse(value: object): value is RevokeTokenResponse {
    return true;
}

export function RevokeTokenResponseFromJSON(json: any): RevokeTokenResponse {
    return RevokeTokenResponseFromJSONTyped(json, false);
}

export function RevokeTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function RevokeTokenResponseToJSON(json: any): RevokeTokenResponse {
    return RevokeTokenResponseToJSONTyped(json, false);
}

export function RevokeTokenResponseToJSONTyped(value?: RevokeTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}
