/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferReversalTransfer } from './TransferReversalTransfer';
import {
    TransferReversalTransferFromJSON,
    TransferReversalTransferFromJSONTyped,
    TransferReversalTransferToJSON,
    TransferReversalTransferToJSONTyped,
} from './TransferReversalTransfer';

/**
 * N/A
 * @export
 * @interface TransferReversal
 */
export interface TransferReversal {
    /**
     * N/A
     * @type {number}
     * @memberof TransferReversal
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransferReversal
     */
    balanceTransaction?: string | null;
    /**
     * N/A
     * @type {number}
     * @memberof TransferReversal
     */
    created: number;
    /**
     * N/A
     * @type {string}
     * @memberof TransferReversal
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof TransferReversal
     */
    destinationPaymentRefund?: string | null;
    /**
     * N/A
     * @type {string}
     * @memberof TransferReversal
     */
    id: string;
    /**
     * N/A
     * @type {object}
     * @memberof TransferReversal
     */
    metadata?: object;
    /**
     * N/A
     * @type {TransferReversalObjectEnum}
     * @memberof TransferReversal
     */
    object: TransferReversalObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof TransferReversal
     */
    sourceRefund?: string | null;
    /**
     * 
     * @type {TransferReversalTransfer}
     * @memberof TransferReversal
     */
    transfer: TransferReversalTransfer;
}


/**
 * @export
 */
export const TransferReversalObjectEnum = {
    TransferReversal: 'transfer_reversal'
} as const;
export type TransferReversalObjectEnum = typeof TransferReversalObjectEnum[keyof typeof TransferReversalObjectEnum];


/**
 * Check if a given object implements the TransferReversal interface.
 */
export function instanceOfTransferReversal(value: object): value is TransferReversal {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('transfer' in value) || value['transfer'] === undefined) return false;
    return true;
}

export function TransferReversalFromJSON(json: any): TransferReversal {
    return TransferReversalFromJSONTyped(json, false);
}

export function TransferReversalFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferReversal {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'balanceTransaction': json['balance_transaction'] == null ? undefined : json['balance_transaction'],
        'created': json['created'],
        'currency': json['currency'],
        'destinationPaymentRefund': json['destination_payment_refund'] == null ? undefined : json['destination_payment_refund'],
        'id': json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'object': json['object'],
        'sourceRefund': json['source_refund'] == null ? undefined : json['source_refund'],
        'transfer': TransferReversalTransferFromJSON(json['transfer']),
    };
}

export function TransferReversalToJSON(json: any): TransferReversal {
    return TransferReversalToJSONTyped(json, false);
}

export function TransferReversalToJSONTyped(value?: TransferReversal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'balance_transaction': value['balanceTransaction'],
        'created': value['created'],
        'currency': value['currency'],
        'destination_payment_refund': value['destinationPaymentRefund'],
        'id': value['id'],
        'metadata': value['metadata'],
        'object': value['object'],
        'source_refund': value['sourceRefund'],
        'transfer': TransferReversalTransferToJSON(value['transfer']),
    };
}

