/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferEventListPost200ResponseTransferEventsInner } from './TransferEventListPost200ResponseTransferEventsInner';
import {
    TransferEventListPost200ResponseTransferEventsInnerFromJSON,
    TransferEventListPost200ResponseTransferEventsInnerFromJSONTyped,
    TransferEventListPost200ResponseTransferEventsInnerToJSON,
    TransferEventListPost200ResponseTransferEventsInnerToJSONTyped,
} from './TransferEventListPost200ResponseTransferEventsInner';

/**
 * 
 * @export
 * @interface TransferEventListPost200Response
 */
export interface TransferEventListPost200Response {
    /**
     * 
     * @type {Array<TransferEventListPost200ResponseTransferEventsInner>}
     * @memberof TransferEventListPost200Response
     */
    transferEvents?: Array<TransferEventListPost200ResponseTransferEventsInner>;
    /**
     * 
     * @type {string}
     * @memberof TransferEventListPost200Response
     */
    requestId?: string;
}

/**
 * Check if a given object implements the TransferEventListPost200Response interface.
 */
export function instanceOfTransferEventListPost200Response(value: object): value is TransferEventListPost200Response {
    return true;
}

export function TransferEventListPost200ResponseFromJSON(json: any): TransferEventListPost200Response {
    return TransferEventListPost200ResponseFromJSONTyped(json, false);
}

export function TransferEventListPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferEventListPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'transferEvents': json['transfer_events'] == null ? undefined : ((json['transfer_events'] as Array<any>).map(TransferEventListPost200ResponseTransferEventsInnerFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function TransferEventListPost200ResponseToJSON(json: any): TransferEventListPost200Response {
    return TransferEventListPost200ResponseToJSONTyped(json, false);
}

export function TransferEventListPost200ResponseToJSONTyped(value?: TransferEventListPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transfer_events': value['transferEvents'] == null ? undefined : ((value['transferEvents'] as Array<any>).map(TransferEventListPost200ResponseTransferEventsInnerToJSON)),
        'request_id': value['requestId'],
    };
}

