/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferRecurringCreatePost200ResponseRecurringTransferSchedule
 */
export interface TransferRecurringCreatePost200ResponseRecurringTransferSchedule {
    /**
     * 
     * @type {Date}
     * @memberof TransferRecurringCreatePost200ResponseRecurringTransferSchedule
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransferRecurringCreatePost200ResponseRecurringTransferSchedule
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof TransferRecurringCreatePost200ResponseRecurringTransferSchedule
     */
    intervalUnit?: string;
    /**
     * 
     * @type {number}
     * @memberof TransferRecurringCreatePost200ResponseRecurringTransferSchedule
     */
    intervalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TransferRecurringCreatePost200ResponseRecurringTransferSchedule
     */
    intervalExecutionDay?: number;
}

/**
 * Check if a given object implements the TransferRecurringCreatePost200ResponseRecurringTransferSchedule interface.
 */
export function instanceOfTransferRecurringCreatePost200ResponseRecurringTransferSchedule(value: object): value is TransferRecurringCreatePost200ResponseRecurringTransferSchedule {
    return true;
}

export function TransferRecurringCreatePost200ResponseRecurringTransferScheduleFromJSON(json: any): TransferRecurringCreatePost200ResponseRecurringTransferSchedule {
    return TransferRecurringCreatePost200ResponseRecurringTransferScheduleFromJSONTyped(json, false);
}

export function TransferRecurringCreatePost200ResponseRecurringTransferScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRecurringCreatePost200ResponseRecurringTransferSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'intervalUnit': json['interval_unit'] == null ? undefined : json['interval_unit'],
        'intervalCount': json['interval_count'] == null ? undefined : json['interval_count'],
        'intervalExecutionDay': json['interval_execution_day'] == null ? undefined : json['interval_execution_day'],
    };
}

export function TransferRecurringCreatePost200ResponseRecurringTransferScheduleToJSON(json: any): TransferRecurringCreatePost200ResponseRecurringTransferSchedule {
    return TransferRecurringCreatePost200ResponseRecurringTransferScheduleToJSONTyped(json, false);
}

export function TransferRecurringCreatePost200ResponseRecurringTransferScheduleToJSONTyped(value?: TransferRecurringCreatePost200ResponseRecurringTransferSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'interval_unit': value['intervalUnit'],
        'interval_count': value['intervalCount'],
        'interval_execution_day': value['intervalExecutionDay'],
    };
}

