/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferPlatformRequirementSubmitPost200ResponseOriginator
 */
export interface TransferPlatformRequirementSubmitPost200ResponseOriginator {
    /**
     * 
     * @type {string}
     * @memberof TransferPlatformRequirementSubmitPost200ResponseOriginator
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferPlatformRequirementSubmitPost200ResponseOriginator
     */
    transferDiligenceStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferPlatformRequirementSubmitPost200ResponseOriginator
     */
    companyName?: string;
}

/**
 * Check if a given object implements the TransferPlatformRequirementSubmitPost200ResponseOriginator interface.
 */
export function instanceOfTransferPlatformRequirementSubmitPost200ResponseOriginator(value: object): value is TransferPlatformRequirementSubmitPost200ResponseOriginator {
    return true;
}

export function TransferPlatformRequirementSubmitPost200ResponseOriginatorFromJSON(json: any): TransferPlatformRequirementSubmitPost200ResponseOriginator {
    return TransferPlatformRequirementSubmitPost200ResponseOriginatorFromJSONTyped(json, false);
}

export function TransferPlatformRequirementSubmitPost200ResponseOriginatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferPlatformRequirementSubmitPost200ResponseOriginator {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'transferDiligenceStatus': json['transfer_diligence_status'] == null ? undefined : json['transfer_diligence_status'],
        'companyName': json['company_name'] == null ? undefined : json['company_name'],
    };
}

export function TransferPlatformRequirementSubmitPost200ResponseOriginatorToJSON(json: any): TransferPlatformRequirementSubmitPost200ResponseOriginator {
    return TransferPlatformRequirementSubmitPost200ResponseOriginatorToJSONTyped(json, false);
}

export function TransferPlatformRequirementSubmitPost200ResponseOriginatorToJSONTyped(value?: TransferPlatformRequirementSubmitPost200ResponseOriginator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'transfer_diligence_status': value['transferDiligenceStatus'],
        'company_name': value['companyName'],
    };
}

