/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferGetPost200ResponseTransferFailureReason
 */
export interface TransferGetPost200ResponseTransferFailureReason {
    /**
     * 
     * @type {string}
     * @memberof TransferGetPost200ResponseTransferFailureReason
     */
    achReturnCode?: string;
}

/**
 * Check if a given object implements the TransferGetPost200ResponseTransferFailureReason interface.
 */
export function instanceOfTransferGetPost200ResponseTransferFailureReason(value: object): value is TransferGetPost200ResponseTransferFailureReason {
    return true;
}

export function TransferGetPost200ResponseTransferFailureReasonFromJSON(json: any): TransferGetPost200ResponseTransferFailureReason {
    return TransferGetPost200ResponseTransferFailureReasonFromJSONTyped(json, false);
}

export function TransferGetPost200ResponseTransferFailureReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferGetPost200ResponseTransferFailureReason {
    if (json == null) {
        return json;
    }
    return {
        
        'achReturnCode': json['ach_return_code'] == null ? undefined : json['ach_return_code'],
    };
}

export function TransferGetPost200ResponseTransferFailureReasonToJSON(json: any): TransferGetPost200ResponseTransferFailureReason {
    return TransferGetPost200ResponseTransferFailureReasonToJSONTyped(json, false);
}

export function TransferGetPost200ResponseTransferFailureReasonToJSONTyped(value?: TransferGetPost200ResponseTransferFailureReason | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ach_return_code': value['achReturnCode'],
    };
}

