/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferSweepGetPost200ResponseSweep
 */
export interface TransferSweepGetPost200ResponseSweep {
    /**
     * 
     * @type {string}
     * @memberof TransferSweepGetPost200ResponseSweep
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof TransferSweepGetPost200ResponseSweep
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof TransferSweepGetPost200ResponseSweep
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferSweepGetPost200ResponseSweep
     */
    isoCurrencyCode?: string;
}

/**
 * Check if a given object implements the TransferSweepGetPost200ResponseSweep interface.
 */
export function instanceOfTransferSweepGetPost200ResponseSweep(value: object): value is TransferSweepGetPost200ResponseSweep {
    return true;
}

export function TransferSweepGetPost200ResponseSweepFromJSON(json: any): TransferSweepGetPost200ResponseSweep {
    return TransferSweepGetPost200ResponseSweepFromJSONTyped(json, false);
}

export function TransferSweepGetPost200ResponseSweepFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferSweepGetPost200ResponseSweep {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'isoCurrencyCode': json['iso_currency_code'] == null ? undefined : json['iso_currency_code'],
    };
}

export function TransferSweepGetPost200ResponseSweepToJSON(json: any): TransferSweepGetPost200ResponseSweep {
    return TransferSweepGetPost200ResponseSweepToJSONTyped(json, false);
}

export function TransferSweepGetPost200ResponseSweepToJSONTyped(value?: TransferSweepGetPost200ResponseSweep | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'] == null ? value['created'] : value['created'].toISOString(),
        'amount': value['amount'],
        'iso_currency_code': value['isoCurrencyCode'],
    };
}

