/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferRecurringCreatePost200ResponseRecurringTransfer } from './TransferRecurringCreatePost200ResponseRecurringTransfer';
import {
    TransferRecurringCreatePost200ResponseRecurringTransferFromJSON,
    TransferRecurringCreatePost200ResponseRecurringTransferFromJSONTyped,
    TransferRecurringCreatePost200ResponseRecurringTransferToJSON,
    TransferRecurringCreatePost200ResponseRecurringTransferToJSONTyped,
} from './TransferRecurringCreatePost200ResponseRecurringTransfer';

/**
 * 
 * @export
 * @interface TransferRecurringCreatePost200Response
 */
export interface TransferRecurringCreatePost200Response {
    /**
     * 
     * @type {TransferRecurringCreatePost200ResponseRecurringTransfer}
     * @memberof TransferRecurringCreatePost200Response
     */
    recurringTransfer?: TransferRecurringCreatePost200ResponseRecurringTransfer;
    /**
     * 
     * @type {string}
     * @memberof TransferRecurringCreatePost200Response
     */
    decision?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferRecurringCreatePost200Response
     */
    requestId?: string;
}

/**
 * Check if a given object implements the TransferRecurringCreatePost200Response interface.
 */
export function instanceOfTransferRecurringCreatePost200Response(value: object): value is TransferRecurringCreatePost200Response {
    return true;
}

export function TransferRecurringCreatePost200ResponseFromJSON(json: any): TransferRecurringCreatePost200Response {
    return TransferRecurringCreatePost200ResponseFromJSONTyped(json, false);
}

export function TransferRecurringCreatePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRecurringCreatePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'recurringTransfer': json['recurring_transfer'] == null ? undefined : TransferRecurringCreatePost200ResponseRecurringTransferFromJSON(json['recurring_transfer']),
        'decision': json['decision'] == null ? undefined : json['decision'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function TransferRecurringCreatePost200ResponseToJSON(json: any): TransferRecurringCreatePost200Response {
    return TransferRecurringCreatePost200ResponseToJSONTyped(json, false);
}

export function TransferRecurringCreatePost200ResponseToJSONTyped(value?: TransferRecurringCreatePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recurring_transfer': TransferRecurringCreatePost200ResponseRecurringTransferToJSON(value['recurringTransfer']),
        'decision': value['decision'],
        'request_id': value['requestId'],
    };
}

