/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks } from './TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks';
import {
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksFromJSON,
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksFromJSONTyped,
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksToJSON,
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksToJSONTyped,
} from './TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks';

/**
 * 
 * @export
 * @interface TransferCapabilitiesGetPost200Response
 */
export interface TransferCapabilitiesGetPost200Response {
    /**
     * 
     * @type {TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks}
     * @memberof TransferCapabilitiesGetPost200Response
     */
    institutionSupportedNetworks?: TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks;
    /**
     * 
     * @type {string}
     * @memberof TransferCapabilitiesGetPost200Response
     */
    requestId?: string;
}

/**
 * Check if a given object implements the TransferCapabilitiesGetPost200Response interface.
 */
export function instanceOfTransferCapabilitiesGetPost200Response(value: object): value is TransferCapabilitiesGetPost200Response {
    return true;
}

export function TransferCapabilitiesGetPost200ResponseFromJSON(json: any): TransferCapabilitiesGetPost200Response {
    return TransferCapabilitiesGetPost200ResponseFromJSONTyped(json, false);
}

export function TransferCapabilitiesGetPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferCapabilitiesGetPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'institutionSupportedNetworks': json['institution_supported_networks'] == null ? undefined : TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksFromJSON(json['institution_supported_networks']),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function TransferCapabilitiesGetPost200ResponseToJSON(json: any): TransferCapabilitiesGetPost200Response {
    return TransferCapabilitiesGetPost200ResponseToJSONTyped(json, false);
}

export function TransferCapabilitiesGetPost200ResponseToJSONTyped(value?: TransferCapabilitiesGetPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'institution_supported_networks': TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksToJSON(value['institutionSupportedNetworks']),
        'request_id': value['requestId'],
    };
}

