/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtp } from './TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtp';
import {
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtpFromJSON,
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtpFromJSONTyped,
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtpToJSON,
    TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtpToJSONTyped,
} from './TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtp';

/**
 * 
 * @export
 * @interface TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks
 */
export interface TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks {
    /**
     * 
     * @type {TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtp}
     * @memberof TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks
     */
    rtp?: TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtp;
}

/**
 * Check if a given object implements the TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks interface.
 */
export function instanceOfTransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks(value: object): value is TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks {
    return true;
}

export function TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksFromJSON(json: any): TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks {
    return TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksFromJSONTyped(json, false);
}

export function TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks {
    if (json == null) {
        return json;
    }
    return {
        
        'rtp': json['rtp'] == null ? undefined : TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtpFromJSON(json['rtp']),
    };
}

export function TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksToJSON(json: any): TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks {
    return TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksToJSONTyped(json, false);
}

export function TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksToJSONTyped(value?: TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rtp': TransferCapabilitiesGetPost200ResponseInstitutionSupportedNetworksRtpToJSON(value['rtp']),
    };
}

