/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface TransferReversalList
 */
export interface TransferReversalList {
    /**
     * N/A
     * @type {Array<any>}
     * @memberof TransferReversalList
     */
    data: Array<any>;
    /**
     * N/A
     * @type {boolean}
     * @memberof TransferReversalList
     */
    hasMore: boolean;
    /**
     * N/A
     * @type {TransferReversalListObjectEnum}
     * @memberof TransferReversalList
     */
    object: TransferReversalListObjectEnum;
    /**
     * N/A
     * @type {string}
     * @memberof TransferReversalList
     */
    url: string;
}


/**
 * @export
 */
export const TransferReversalListObjectEnum = {
    List: 'list'
} as const;
export type TransferReversalListObjectEnum = typeof TransferReversalListObjectEnum[keyof typeof TransferReversalListObjectEnum];


/**
 * Check if a given object implements the TransferReversalList interface.
 */
export function instanceOfTransferReversalList(value: object): value is TransferReversalList {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function TransferReversalListFromJSON(json: any): TransferReversalList {
    return TransferReversalListFromJSONTyped(json, false);
}

export function TransferReversalListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferReversalList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'hasMore': json['has_more'],
        'object': json['object'],
        'url': json['url'],
    };
}

export function TransferReversalListToJSON(json: any): TransferReversalList {
    return TransferReversalListToJSONTyped(json, false);
}

export function TransferReversalListToJSONTyped(value?: TransferReversalList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'has_more': value['hasMore'],
        'object': value['object'],
        'url': value['url'],
    };
}

