/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddress } from './TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddress';
import {
    TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddressFromJSON,
    TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddressFromJSONTyped,
    TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddressToJSON,
    TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddressToJSONTyped,
} from './TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddress';

/**
 * 
 * @export
 * @interface TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser
 */
export interface TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser {
    /**
     * 
     * @type {string}
     * @memberof TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser
     */
    legalName?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser
     */
    emailAddress?: string;
    /**
     * 
     * @type {TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddress}
     * @memberof TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser
     */
    address?: TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddress;
}

/**
 * Check if a given object implements the TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser interface.
 */
export function instanceOfTransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser(value: object): value is TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser {
    return true;
}

export function TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserFromJSON(json: any): TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser {
    return TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserFromJSONTyped(json, false);
}

export function TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser {
    if (json == null) {
        return json;
    }
    return {
        
        'legalName': json['legal_name'] == null ? undefined : json['legal_name'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'emailAddress': json['email_address'] == null ? undefined : json['email_address'],
        'address': json['address'] == null ? undefined : TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddressFromJSON(json['address']),
    };
}

export function TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserToJSON(json: any): TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser {
    return TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserToJSONTyped(json, false);
}

export function TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserToJSONTyped(value?: TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'legal_name': value['legalName'],
        'phone_number': value['phoneNumber'],
        'email_address': value['emailAddress'],
        'address': TransferAuthorizationCreatePost200ResponseAuthorizationProposedTransferUserAddressToJSON(value['address']),
    };
}

