/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface TransferSchedule
 */
export interface TransferSchedule {
    /**
     * N/A
     * @type {number}
     * @memberof TransferSchedule
     */
    delayDays: number;
    /**
     * N/A
     * @type {string}
     * @memberof TransferSchedule
     */
    interval: string;
    /**
     * N/A
     * @type {number}
     * @memberof TransferSchedule
     */
    monthlyAnchor?: number;
    /**
     * N/A
     * @type {Array<number>}
     * @memberof TransferSchedule
     */
    monthlyPayoutDays?: Array<number>;
    /**
     * N/A
     * @type {string}
     * @memberof TransferSchedule
     */
    weeklyAnchor?: string;
    /**
     * N/A
     * @type {Array<string>}
     * @memberof TransferSchedule
     */
    weeklyPayoutDays?: Array<string>;
}

/**
 * Check if a given object implements the TransferSchedule interface.
 */
export function instanceOfTransferSchedule(value: object): value is TransferSchedule {
    if (!('delayDays' in value) || value['delayDays'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    return true;
}

export function TransferScheduleFromJSON(json: any): TransferSchedule {
    return TransferScheduleFromJSONTyped(json, false);
}

export function TransferScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'delayDays': json['delay_days'],
        'interval': json['interval'],
        'monthlyAnchor': json['monthly_anchor'] == null ? undefined : json['monthly_anchor'],
        'monthlyPayoutDays': json['monthly_payout_days'] == null ? undefined : json['monthly_payout_days'],
        'weeklyAnchor': json['weekly_anchor'] == null ? undefined : json['weekly_anchor'],
        'weeklyPayoutDays': json['weekly_payout_days'] == null ? undefined : json['weekly_payout_days'],
    };
}

export function TransferScheduleToJSON(json: any): TransferSchedule {
    return TransferScheduleToJSONTyped(json, false);
}

export function TransferScheduleToJSONTyped(value?: TransferSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delay_days': value['delayDays'],
        'interval': value['interval'],
        'monthly_anchor': value['monthlyAnchor'],
        'monthly_payout_days': value['monthlyPayoutDays'],
        'weekly_anchor': value['weeklyAnchor'],
        'weekly_payout_days': value['weeklyPayoutDays'],
    };
}

