/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersPasswordResetConfirmPostRequest
 */
export interface UsersPasswordResetConfirmPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersPasswordResetConfirmPostRequest
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPasswordResetConfirmPostRequest
     */
    verificationCode: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPasswordResetConfirmPostRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the UsersPasswordResetConfirmPostRequest interface.
 */
export function instanceOfUsersPasswordResetConfirmPostRequest(value: object): value is UsersPasswordResetConfirmPostRequest {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('verificationCode' in value) || value['verificationCode'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function UsersPasswordResetConfirmPostRequestFromJSON(json: any): UsersPasswordResetConfirmPostRequest {
    return UsersPasswordResetConfirmPostRequestFromJSONTyped(json, false);
}

export function UsersPasswordResetConfirmPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPasswordResetConfirmPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'verificationCode': json['verificationCode'],
        'newPassword': json['newPassword'],
    };
}

export function UsersPasswordResetConfirmPostRequestToJSON(json: any): UsersPasswordResetConfirmPostRequest {
    return UsersPasswordResetConfirmPostRequestToJSONTyped(json, false);
}

export function UsersPasswordResetConfirmPostRequestToJSONTyped(value?: UsersPasswordResetConfirmPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'verificationCode': value['verificationCode'],
        'newPassword': value['newPassword'],
    };
}

