/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersRegisterPostRequestAddress } from './UsersRegisterPostRequestAddress';
import {
    UsersRegisterPostRequestAddressFromJSON,
    UsersRegisterPostRequestAddressFromJSONTyped,
    UsersRegisterPostRequestAddressToJSON,
    UsersRegisterPostRequestAddressToJSONTyped,
} from './UsersRegisterPostRequestAddress';

/**
 * 
 * @export
 * @interface UsersRegisterPostRequest
 */
export interface UsersRegisterPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersRegisterPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UsersRegisterPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UsersRegisterPostRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UsersRegisterPostRequest
     */
    phone?: string;
    /**
     * 
     * @type {UsersRegisterPostRequestAddress}
     * @memberof UsersRegisterPostRequest
     */
    address?: UsersRegisterPostRequestAddress;
}

/**
 * Check if a given object implements the UsersRegisterPostRequest interface.
 */
export function instanceOfUsersRegisterPostRequest(value: object): value is UsersRegisterPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UsersRegisterPostRequestFromJSON(json: any): UsersRegisterPostRequest {
    return UsersRegisterPostRequestFromJSONTyped(json, false);
}

export function UsersRegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersRegisterPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : UsersRegisterPostRequestAddressFromJSON(json['address']),
    };
}

export function UsersRegisterPostRequestToJSON(json: any): UsersRegisterPostRequest {
    return UsersRegisterPostRequestToJSONTyped(json, false);
}

export function UsersRegisterPostRequestToJSONTyped(value?: UsersRegisterPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
        'phone': value['phone'],
        'address': UsersRegisterPostRequestAddressToJSON(value['address']),
    };
}

