/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersMeDevicesGet200ResponseDataInner } from './UsersMeDevicesGet200ResponseDataInner';
import {
    UsersMeDevicesGet200ResponseDataInnerFromJSON,
    UsersMeDevicesGet200ResponseDataInnerFromJSONTyped,
    UsersMeDevicesGet200ResponseDataInnerToJSON,
    UsersMeDevicesGet200ResponseDataInnerToJSONTyped,
} from './UsersMeDevicesGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface UsersMeDevicesGet200Response
 */
export interface UsersMeDevicesGet200Response {
    /**
     * 
     * @type {number}
     * @memberof UsersMeDevicesGet200Response
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof UsersMeDevicesGet200Response
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof UsersMeDevicesGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof UsersMeDevicesGet200Response
     */
    nextOffset?: number;
    /**
     * 
     * @type {Array<UsersMeDevicesGet200ResponseDataInner>}
     * @memberof UsersMeDevicesGet200Response
     */
    data: Array<UsersMeDevicesGet200ResponseDataInner>;
}

/**
 * Check if a given object implements the UsersMeDevicesGet200Response interface.
 */
export function instanceOfUsersMeDevicesGet200Response(value: object): value is UsersMeDevicesGet200Response {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UsersMeDevicesGet200ResponseFromJSON(json: any): UsersMeDevicesGet200Response {
    return UsersMeDevicesGet200ResponseFromJSONTyped(json, false);
}

export function UsersMeDevicesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeDevicesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
        'nextOffset': json['nextOffset'] == null ? undefined : json['nextOffset'],
        'data': ((json['data'] as Array<any>).map(UsersMeDevicesGet200ResponseDataInnerFromJSON)),
    };
}

export function UsersMeDevicesGet200ResponseToJSON(json: any): UsersMeDevicesGet200Response {
    return UsersMeDevicesGet200ResponseToJSONTyped(json, false);
}

export function UsersMeDevicesGet200ResponseToJSONTyped(value?: UsersMeDevicesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
        'nextOffset': value['nextOffset'],
        'data': ((value['data'] as Array<any>).map(UsersMeDevicesGet200ResponseDataInnerToJSON)),
    };
}

