/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserUpdatePostRequestIdentity } from './UserUpdatePostRequestIdentity';
import {
    UserUpdatePostRequestIdentityFromJSON,
    UserUpdatePostRequestIdentityFromJSONTyped,
    UserUpdatePostRequestIdentityToJSON,
    UserUpdatePostRequestIdentityToJSONTyped,
} from './UserUpdatePostRequestIdentity';

/**
 * 
 * @export
 * @interface UserUpdatePostRequest
 */
export interface UserUpdatePostRequest {
    /**
     * 
     * @type {string}
     * @memberof UserUpdatePostRequest
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdatePostRequest
     */
    secret?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdatePostRequest
     */
    userToken?: string;
    /**
     * 
     * @type {UserUpdatePostRequestIdentity}
     * @memberof UserUpdatePostRequest
     */
    identity?: UserUpdatePostRequestIdentity;
}

/**
 * Check if a given object implements the UserUpdatePostRequest interface.
 */
export function instanceOfUserUpdatePostRequest(value: object): value is UserUpdatePostRequest {
    return true;
}

export function UserUpdatePostRequestFromJSON(json: any): UserUpdatePostRequest {
    return UserUpdatePostRequestFromJSONTyped(json, false);
}

export function UserUpdatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'userToken': json['user_token'] == null ? undefined : json['user_token'],
        'identity': json['identity'] == null ? undefined : UserUpdatePostRequestIdentityFromJSON(json['identity']),
    };
}

export function UserUpdatePostRequestToJSON(json: any): UserUpdatePostRequest {
    return UserUpdatePostRequestToJSONTyped(json, false);
}

export function UserUpdatePostRequestToJSONTyped(value?: UserUpdatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'secret': value['secret'],
        'user_token': value['userToken'],
        'identity': UserUpdatePostRequestIdentityToJSON(value['identity']),
    };
}

