/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect
 */
export interface V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect
     */
    returnUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect
     */
    failureReason?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect interface.
 */
export function instanceOfV1CheckoutSessionsGetDefaultResponseErrorSourceRedirect(value: object): value is V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect {
    return true;
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceRedirectFromJSON(json: any): V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect {
    return V1CheckoutSessionsGetDefaultResponseErrorSourceRedirectFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceRedirectFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect {
    if (json == null) {
        return json;
    }
    return {
        
        'returnUrl': json['return_url'] == null ? undefined : json['return_url'],
        'status': json['status'] == null ? undefined : json['status'],
        'url': json['url'] == null ? undefined : json['url'],
        'failureReason': json['failure_reason'] == null ? undefined : json['failure_reason'],
    };
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceRedirectToJSON(json: any): V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect {
    return V1CheckoutSessionsGetDefaultResponseErrorSourceRedirectToJSONTyped(json, false);
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceRedirectToJSONTyped(value?: V1CheckoutSessionsGetDefaultResponseErrorSourceRedirect | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'return_url': value['returnUrl'],
        'status': value['status'],
        'url': value['url'],
        'failure_reason': value['failureReason'],
    };
}

