/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay
     */
    setupFutureUsage?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipayFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipayFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipayFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay {
    if (json == null) {
        return json;
    }
    return {
        
        'setupFutureUsage': json['setup_future_usage'] == null ? undefined : json['setup_future_usage'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipayToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipayToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipayToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAlipay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'setup_future_usage': value['setupFutureUsage'],
    };
}

