/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity {
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity
     */
    divideBy?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity
     */
    round?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantityFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantityFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity {
    if (json == null) {
        return json;
    }
    return {
        
        'divideBy': json['divide_by'] == null ? undefined : json['divide_by'],
        'round': json['round'] == null ? undefined : json['round'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantityToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantityToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantityToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceTransformQuantity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'divide_by': value['divideBy'],
        'round': value['round'],
    };
}

