/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring
     */
    interval?: string;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring
     */
    intervalCount?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring
     */
    usageType?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring
     */
    meter?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurringFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurringFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurringFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring {
    if (json == null) {
        return json;
    }
    return {
        
        'interval': json['interval'] == null ? undefined : json['interval'],
        'intervalCount': json['interval_count'] == null ? undefined : json['interval_count'],
        'usageType': json['usage_type'] == null ? undefined : json['usage_type'],
        'meter': json['meter'] == null ? undefined : json['meter'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurringToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurringToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurringToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceRecurring | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interval': value['interval'],
        'interval_count': value['intervalCount'],
        'usage_type': value['usageType'],
        'meter': value['meter'],
    };
}

