/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInner } from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInner';
import {
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInnerFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInnerFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInnerToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInnerToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInner';
import type { V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmount } from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmount';
import {
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmountFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmountFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmountToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmountToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmount';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 {
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmount}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0
     */
    customUnitAmount?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmount;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0
     */
    taxBehavior?: string;
    /**
     * 
     * @type {Array<V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInner>}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0
     */
    tiers?: Array<V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInner>;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0
     */
    unitAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0
     */
    unitAmountDecimal?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 {
    if (json == null) {
        return json;
    }
    return {
        
        'customUnitAmount': json['custom_unit_amount'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmountFromJSON(json['custom_unit_amount']),
        'taxBehavior': json['tax_behavior'] == null ? undefined : json['tax_behavior'],
        'tiers': json['tiers'] == null ? undefined : ((json['tiers'] as Array<any>).map(V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInnerFromJSON)),
        'unitAmount': json['unit_amount'] == null ? undefined : json['unit_amount'],
        'unitAmountDecimal': json['unit_amount_decimal'] == null ? undefined : json['unit_amount_decimal'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_unit_amount': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0CustomUnitAmountToJSON(value['customUnitAmount']),
        'tax_behavior': value['taxBehavior'],
        'tiers': value['tiers'] == null ? undefined : ((value['tiers'] as Array<any>).map(V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0TiersInnerToJSON)),
        'unit_amount': value['unitAmount'],
        'unit_amount_decimal': value['unitAmountDecimal'],
    };
}

