/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner
     */
    value?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInnerFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner {
    return V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInnerFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInnerToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner {
    return V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInnerToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInnerToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerDropdownOptionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'value': value['value'],
    };
}

