/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion {
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion
     */
    amountSubtotal?: number;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion
     */
    amountTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion
     */
    fxRate?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion
     */
    sourceCurrency?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversionFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion {
    return V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversionFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion {
    if (json == null) {
        return json;
    }
    return {
        
        'amountSubtotal': json['amount_subtotal'] == null ? undefined : json['amount_subtotal'],
        'amountTotal': json['amount_total'] == null ? undefined : json['amount_total'],
        'fxRate': json['fx_rate'] == null ? undefined : json['fx_rate'],
        'sourceCurrency': json['source_currency'] == null ? undefined : json['source_currency'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversionToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion {
    return V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversionToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversionToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerCurrencyConversion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_subtotal': value['amountSubtotal'],
        'amount_total': value['amountTotal'],
        'fx_rate': value['fxRate'],
        'source_currency': value['sourceCurrency'],
    };
}

