/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsPost200ResponseTotalDetailsBreakdown } from './V1CheckoutSessionsPost200ResponseTotalDetailsBreakdown';
import {
    V1CheckoutSessionsPost200ResponseTotalDetailsBreakdownFromJSON,
    V1CheckoutSessionsPost200ResponseTotalDetailsBreakdownFromJSONTyped,
    V1CheckoutSessionsPost200ResponseTotalDetailsBreakdownToJSON,
    V1CheckoutSessionsPost200ResponseTotalDetailsBreakdownToJSONTyped,
} from './V1CheckoutSessionsPost200ResponseTotalDetailsBreakdown';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsPost200ResponseTotalDetails
 */
export interface V1CheckoutSessionsPost200ResponseTotalDetails {
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsPost200ResponseTotalDetails
     */
    amountDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsPost200ResponseTotalDetails
     */
    amountTax?: number;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsPost200ResponseTotalDetails
     */
    amountShipping?: number;
    /**
     * 
     * @type {V1CheckoutSessionsPost200ResponseTotalDetailsBreakdown}
     * @memberof V1CheckoutSessionsPost200ResponseTotalDetails
     */
    breakdown?: V1CheckoutSessionsPost200ResponseTotalDetailsBreakdown;
}

/**
 * Check if a given object implements the V1CheckoutSessionsPost200ResponseTotalDetails interface.
 */
export function instanceOfV1CheckoutSessionsPost200ResponseTotalDetails(value: object): value is V1CheckoutSessionsPost200ResponseTotalDetails {
    return true;
}

export function V1CheckoutSessionsPost200ResponseTotalDetailsFromJSON(json: any): V1CheckoutSessionsPost200ResponseTotalDetails {
    return V1CheckoutSessionsPost200ResponseTotalDetailsFromJSONTyped(json, false);
}

export function V1CheckoutSessionsPost200ResponseTotalDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsPost200ResponseTotalDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'amountDiscount': json['amount_discount'] == null ? undefined : json['amount_discount'],
        'amountTax': json['amount_tax'] == null ? undefined : json['amount_tax'],
        'amountShipping': json['amount_shipping'] == null ? undefined : json['amount_shipping'],
        'breakdown': json['breakdown'] == null ? undefined : V1CheckoutSessionsPost200ResponseTotalDetailsBreakdownFromJSON(json['breakdown']),
    };
}

export function V1CheckoutSessionsPost200ResponseTotalDetailsToJSON(json: any): V1CheckoutSessionsPost200ResponseTotalDetails {
    return V1CheckoutSessionsPost200ResponseTotalDetailsToJSONTyped(json, false);
}

export function V1CheckoutSessionsPost200ResponseTotalDetailsToJSONTyped(value?: V1CheckoutSessionsPost200ResponseTotalDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_discount': value['amountDiscount'],
        'amount_tax': value['amountTax'],
        'amount_shipping': value['amountShipping'],
        'breakdown': V1CheckoutSessionsPost200ResponseTotalDetailsBreakdownToJSON(value['breakdown']),
    };
}

