/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress } from './V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress';
import {
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
 */
export interface V1CheckoutSessionsGetDefaultResponseErrorSourceOwner {
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    address?: V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    phone?: string;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    verifiedAddress?: V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    verifiedEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    verifiedName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceOwner
     */
    verifiedPhone?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGetDefaultResponseErrorSourceOwner interface.
 */
export function instanceOfV1CheckoutSessionsGetDefaultResponseErrorSourceOwner(value: object): value is V1CheckoutSessionsGetDefaultResponseErrorSourceOwner {
    return true;
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceOwnerFromJSON(json: any): V1CheckoutSessionsGetDefaultResponseErrorSourceOwner {
    return V1CheckoutSessionsGetDefaultResponseErrorSourceOwnerFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceOwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGetDefaultResponseErrorSourceOwner {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressFromJSON(json['address']),
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'verifiedAddress': json['verified_address'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressFromJSON(json['verified_address']),
        'verifiedEmail': json['verified_email'] == null ? undefined : json['verified_email'],
        'verifiedName': json['verified_name'] == null ? undefined : json['verified_name'],
        'verifiedPhone': json['verified_phone'] == null ? undefined : json['verified_phone'],
    };
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceOwnerToJSON(json: any): V1CheckoutSessionsGetDefaultResponseErrorSourceOwner {
    return V1CheckoutSessionsGetDefaultResponseErrorSourceOwnerToJSONTyped(json, false);
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceOwnerToJSONTyped(value?: V1CheckoutSessionsGetDefaultResponseErrorSourceOwner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressToJSON(value['address']),
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
        'verified_address': V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressToJSON(value['verifiedAddress']),
        'verified_email': value['verifiedEmail'],
        'verified_name': value['verifiedName'],
        'verified_phone': value['verifiedPhone'],
    };
}

