/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel
     */
    custom?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabelFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel {
    return V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabelFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'custom': json['custom'] == null ? undefined : json['custom'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabelToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel {
    return V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabelToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabelToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerCustomFieldsInnerLabel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'custom': value['custom'],
    };
}

