/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerPermissions
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerPermissions {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPermissions
     */
    updateShippingDetails?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerPermissions interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerPermissions(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerPermissions {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerPermissionsFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPermissions {
    return V1CheckoutSessionsGet200ResponseDataInnerPermissionsFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'updateShippingDetails': json['update_shipping_details'] == null ? undefined : json['update_shipping_details'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerPermissionsToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPermissions {
    return V1CheckoutSessionsGet200ResponseDataInnerPermissionsToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPermissionsToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerPermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'update_shipping_details': value['updateShippingDetails'],
    };
}

