/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions
     */
    amountTaxDisplay?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions
     */
    template?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'amountTaxDisplay': json['amount_tax_display'] == null ? undefined : json['amount_tax_display'],
        'template': json['template'] == null ? undefined : json['template'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_tax_display': value['amountTaxDisplay'],
        'template': value['template'],
    };
}

