/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink
     */
    display?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLinkFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink {
    return V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLinkFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink {
    if (json == null) {
        return json;
    }
    return {
        
        'display': json['display'] == null ? undefined : json['display'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLinkToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink {
    return V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLinkToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLinkToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerWalletOptionsLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display': value['display'],
    };
}

