/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner
 */
export interface V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner {
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner
     */
    parent?: string;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner
     */
    type?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner interface.
 */
export function instanceOfV1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner(value: object): value is V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner {
    return true;
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInnerFromJSON(json: any): V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner {
    return V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInnerFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInnerToJSON(json: any): V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner {
    return V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInnerToJSONTyped(json, false);
}

export function V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInnerToJSONTyped(value?: V1CheckoutSessionsGetDefaultResponseErrorSourceSourceOrderItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'parent': value['parent'],
        'quantity': value['quantity'],
        'type': value['type'],
    };
}

