/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions
     */
    allowRedisplayFilters?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions
     */
    paymentMethodRemove?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions
     */
    paymentMethodSave?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptionsFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptionsFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'allowRedisplayFilters': json['allow_redisplay_filters'] == null ? undefined : json['allow_redisplay_filters'],
        'paymentMethodRemove': json['payment_method_remove'] == null ? undefined : json['payment_method_remove'],
        'paymentMethodSave': json['payment_method_save'] == null ? undefined : json['payment_method_save'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptionsToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptionsToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptionsToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerSavedPaymentMethodOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_redisplay_filters': value['allowRedisplayFilters'],
        'payment_method_remove': value['paymentMethodRemove'],
        'payment_method_save': value['paymentMethodSave'],
    };
}

