/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnections } from './V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnections';
import {
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnectionsFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnectionsFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnectionsToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnectionsToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnections';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount {
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnections}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount
     */
    financialConnections?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnections;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount
     */
    setupFutureUsage?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount
     */
    targetDate?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount
     */
    verificationMethod?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'financialConnections': json['financial_connections'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnectionsFromJSON(json['financial_connections']),
        'setupFutureUsage': json['setup_future_usage'] == null ? undefined : json['setup_future_usage'],
        'targetDate': json['target_date'] == null ? undefined : json['target_date'],
        'verificationMethod': json['verification_method'] == null ? undefined : json['verification_method'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'financial_connections': V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsUsBankAccountFinancialConnectionsToJSON(value['financialConnections']),
        'setup_future_usage': value['setupFutureUsage'],
        'target_date': value['targetDate'],
        'verification_method': value['verificationMethod'],
    };
}

