/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm
     */
    captureMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm
     */
    setupFutureUsage?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirmFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirmFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm {
    if (json == null) {
        return json;
    }
    return {
        
        'captureMethod': json['capture_method'] == null ? undefined : json['capture_method'],
        'setupFutureUsage': json['setup_future_usage'] == null ? undefined : json['setup_future_usage'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirmToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirmToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirmToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsAffirm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capture_method': value['captureMethod'],
        'setup_future_usage': value['setupFutureUsage'],
    };
}

