/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiability } from './V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiability';
import {
    V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiabilityFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiabilityFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiabilityToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiabilityToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiability';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax {
    /**
     * 
     * @type {boolean}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax
     */
    enabled?: boolean;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiability}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax
     */
    liability?: V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiability;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax
     */
    status?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerAutomaticTax(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax {
    return V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'liability': json['liability'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiabilityFromJSON(json['liability']),
        'provider': json['provider'] == null ? undefined : json['provider'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax {
    return V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerAutomaticTax | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'liability': V1CheckoutSessionsGet200ResponseDataInnerAutomaticTaxLiabilityToJSON(value['liability']),
        'provider': value['provider'],
        'status': value['status'],
    };
}

