/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRate } from './V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRate';
import {
    V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRateFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRateFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRateToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRateToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRate';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner {
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner
     */
    amount?: number;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRate}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner
     */
    rate?: V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRate;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner
     */
    taxabilityReason?: string;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner
     */
    taxableAmount?: number;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner {
    return V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'rate': json['rate'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRateFromJSON(json['rate']),
        'taxabilityReason': json['taxability_reason'] == null ? undefined : json['taxability_reason'],
        'taxableAmount': json['taxable_amount'] == null ? undefined : json['taxable_amount'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner {
    return V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'rate': V1CheckoutSessionsGet200ResponseDataInnerTotalDetailsBreakdownTaxesInnerRateToJSON(value['rate']),
        'taxability_reason': value['taxabilityReason'],
        'taxable_amount': value['taxableAmount'],
    };
}

