/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix
     */
    amountIncludesIof?: string;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix
     */
    expiresAfterSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix
     */
    setupFutureUsage?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPixFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPixFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPixFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix {
    if (json == null) {
        return json;
    }
    return {
        
        'amountIncludesIof': json['amount_includes_iof'] == null ? undefined : json['amount_includes_iof'],
        'expiresAfterSeconds': json['expires_after_seconds'] == null ? undefined : json['expires_after_seconds'],
        'setupFutureUsage': json['setup_future_usage'] == null ? undefined : json['setup_future_usage'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPixToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPixToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPixToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsPix | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_includes_iof': value['amountIncludesIof'],
        'expires_after_seconds': value['expiresAfterSeconds'],
        'setup_future_usage': value['setupFutureUsage'],
    };
}

