/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransfer } from './V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransfer';
import {
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransferFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransferFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransferToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransferToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransfer';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance {
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransfer}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance
     */
    bankTransfer?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransfer;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance
     */
    fundingType?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance
     */
    setupFutureUsage?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance {
    if (json == null) {
        return json;
    }
    return {
        
        'bankTransfer': json['bank_transfer'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransferFromJSON(json['bank_transfer']),
        'fundingType': json['funding_type'] == null ? undefined : json['funding_type'],
        'setupFutureUsage': json['setup_future_usage'] == null ? undefined : json['setup_future_usage'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_transfer': V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsCustomerBalanceBankTransferToJSON(value['bankTransfer']),
        'funding_type': value['fundingType'],
        'setup_future_usage': value['setupFutureUsage'],
    };
}

