/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection {
    /**
     * 
     * @type {boolean}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection
     */
    required?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollectionFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection {
    return V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollectionFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'required': json['required'] == null ? undefined : json['required'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollectionToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection {
    return V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollectionToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollectionToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerTaxIdCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'required': value['required'],
    };
}

