/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions
     */
    referencePrefix?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptionsFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptionsFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'referencePrefix': json['reference_prefix'] == null ? undefined : json['reference_prefix'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptionsToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptionsToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptionsToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerPaymentMethodOptionsBacsDebitMandateOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference_prefix': value['referencePrefix'],
    };
}

