/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 } from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0';
import {
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0';

/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions {
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions
     */
    key0?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions
     */
    key1?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions
     */
    key2?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions
     */
    key3?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions
     */
    key4?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'key0': json['key_0'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_0']),
        'key1': json['key_1'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_1']),
        'key2': json['key_2'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_2']),
        'key3': json['key_3'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_3']),
        'key4': json['key_4'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_4']),
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions {
    return V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_0': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key0']),
        'key_1': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key1']),
        'key_2': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key2']),
        'key_3': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key3']),
        'key_4': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key4']),
    };
}

