/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery
 */
export interface V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery {
    /**
     * 
     * @type {boolean}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery
     */
    allowPromotionCodes?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery
     */
    expiresAt?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery
     */
    url?: string;
}

/**
 * Check if a given object implements the V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery interface.
 */
export function instanceOfV1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery(value: object): value is V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery {
    return true;
}

export function V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecoveryFromJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery {
    return V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecoveryFromJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecoveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery {
    if (json == null) {
        return json;
    }
    return {
        
        'allowPromotionCodes': json['allow_promotion_codes'] == null ? undefined : json['allow_promotion_codes'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecoveryToJSON(json: any): V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery {
    return V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecoveryToJSONTyped(json, false);
}

export function V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecoveryToJSONTyped(value?: V1CheckoutSessionsGet200ResponseDataInnerAfterExpirationRecovery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_promotion_codes': value['allowPromotionCodes'],
        'enabled': value['enabled'],
        'expires_at': value['expiresAt'],
        'url': value['url'],
    };
}

