/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInner } from './V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInner';
import {
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInnerFromJSON,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInnerFromJSONTyped,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInnerToJSON,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInnerToJSONTyped,
} from './V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInner';
import type { V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier } from './V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier';
import {
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierFromJSON,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierFromJSONTyped,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierToJSON,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierToJSONTyped,
} from './V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier';

/**
 * 
 * @export
 * @interface V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner
 */
export interface V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner {
    /**
     * 
     * @type {number}
     * @memberof V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner
     */
    deliveredAt?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner
     */
    metricTons?: string;
    /**
     * 
     * @type {V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier}
     * @memberof V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner
     */
    supplier?: V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier;
    /**
     * 
     * @type {V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInner}
     * @memberof V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner
     */
    location?: V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInner;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner
     */
    registryUrl?: string;
}

/**
 * Check if a given object implements the V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner interface.
 */
export function instanceOfV1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner(value: object): value is V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner {
    return true;
}

export function V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerFromJSON(json: any): V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner {
    return V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerFromJSONTyped(json, false);
}

export function V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'deliveredAt': json['delivered_at'] == null ? undefined : json['delivered_at'],
        'metricTons': json['metric_tons'] == null ? undefined : json['metric_tons'],
        'supplier': json['supplier'] == null ? undefined : V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierFromJSON(json['supplier']),
        'location': json['location'] == null ? undefined : V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInnerFromJSON(json['location']),
        'registryUrl': json['registry_url'] == null ? undefined : json['registry_url'],
    };
}

export function V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerToJSON(json: any): V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner {
    return V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerToJSONTyped(json, false);
}

export function V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerToJSONTyped(value?: V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delivered_at': value['deliveredAt'],
        'metric_tons': value['metricTons'],
        'supplier': V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierToJSON(value['supplier']),
        'location': V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierLocationsInnerToJSON(value['location']),
        'registry_url': value['registryUrl'],
    };
}

