/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ClimateProductsGet200ResponseDataInner } from './V1ClimateProductsGet200ResponseDataInner';
import {
    V1ClimateProductsGet200ResponseDataInnerFromJSON,
    V1ClimateProductsGet200ResponseDataInnerFromJSONTyped,
    V1ClimateProductsGet200ResponseDataInnerToJSON,
    V1ClimateProductsGet200ResponseDataInnerToJSONTyped,
} from './V1ClimateProductsGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface V1ClimateProductsGet200Response
 */
export interface V1ClimateProductsGet200Response {
    /**
     * 
     * @type {Array<V1ClimateProductsGet200ResponseDataInner>}
     * @memberof V1ClimateProductsGet200Response
     */
    data?: Array<V1ClimateProductsGet200ResponseDataInner>;
    /**
     * 
     * @type {boolean}
     * @memberof V1ClimateProductsGet200Response
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateProductsGet200Response
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateProductsGet200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the V1ClimateProductsGet200Response interface.
 */
export function instanceOfV1ClimateProductsGet200Response(value: object): value is V1ClimateProductsGet200Response {
    return true;
}

export function V1ClimateProductsGet200ResponseFromJSON(json: any): V1ClimateProductsGet200Response {
    return V1ClimateProductsGet200ResponseFromJSONTyped(json, false);
}

export function V1ClimateProductsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ClimateProductsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V1ClimateProductsGet200ResponseDataInnerFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'object': json['object'] == null ? undefined : json['object'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function V1ClimateProductsGet200ResponseToJSON(json: any): V1ClimateProductsGet200Response {
    return V1ClimateProductsGet200ResponseToJSONTyped(json, false);
}

export function V1ClimateProductsGet200ResponseToJSONTyped(value?: V1ClimateProductsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V1ClimateProductsGet200ResponseDataInnerToJSON)),
        'has_more': value['hasMore'],
        'object': value['object'],
        'url': value['url'],
    };
}

