/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier } from './V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier';
import {
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierFromJSON,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierFromJSONTyped,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierToJSON,
    V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierToJSONTyped,
} from './V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier';
import type { V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTon } from './V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTon';
import {
    V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTonFromJSON,
    V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTonFromJSONTyped,
    V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTonToJSON,
    V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTonToJSONTyped,
} from './V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTon';

/**
 * 
 * @export
 * @interface V1ClimateProductsGet200ResponseDataInner
 */
export interface V1ClimateProductsGet200ResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    created?: number;
    /**
     * 
     * @type {V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTon}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    currentPricesPerMetricTon?: V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTon;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    livemode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    metricTonsAvailable?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    object?: string;
    /**
     * 
     * @type {Array<V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier>}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    suppliers?: Array<V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplier>;
    /**
     * 
     * @type {number}
     * @memberof V1ClimateProductsGet200ResponseDataInner
     */
    deliveryYear?: number;
}

/**
 * Check if a given object implements the V1ClimateProductsGet200ResponseDataInner interface.
 */
export function instanceOfV1ClimateProductsGet200ResponseDataInner(value: object): value is V1ClimateProductsGet200ResponseDataInner {
    return true;
}

export function V1ClimateProductsGet200ResponseDataInnerFromJSON(json: any): V1ClimateProductsGet200ResponseDataInner {
    return V1ClimateProductsGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function V1ClimateProductsGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ClimateProductsGet200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'currentPricesPerMetricTon': json['current_prices_per_metric_ton'] == null ? undefined : V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTonFromJSON(json['current_prices_per_metric_ton']),
        'id': json['id'] == null ? undefined : json['id'],
        'livemode': json['livemode'] == null ? undefined : json['livemode'],
        'metricTonsAvailable': json['metric_tons_available'] == null ? undefined : json['metric_tons_available'],
        'name': json['name'] == null ? undefined : json['name'],
        'object': json['object'] == null ? undefined : json['object'],
        'suppliers': json['suppliers'] == null ? undefined : ((json['suppliers'] as Array<any>).map(V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierFromJSON)),
        'deliveryYear': json['delivery_year'] == null ? undefined : json['delivery_year'],
    };
}

export function V1ClimateProductsGet200ResponseDataInnerToJSON(json: any): V1ClimateProductsGet200ResponseDataInner {
    return V1ClimateProductsGet200ResponseDataInnerToJSONTyped(json, false);
}

export function V1ClimateProductsGet200ResponseDataInnerToJSONTyped(value?: V1ClimateProductsGet200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'current_prices_per_metric_ton': V1ClimateProductsGet200ResponseDataInnerCurrentPricesPerMetricTonToJSON(value['currentPricesPerMetricTon']),
        'id': value['id'],
        'livemode': value['livemode'],
        'metric_tons_available': value['metricTonsAvailable'],
        'name': value['name'],
        'object': value['object'],
        'suppliers': value['suppliers'] == null ? undefined : ((value['suppliers'] as Array<any>).map(V1ClimateOrdersGet200ResponseDataInnerDeliveryDetailsInnerSupplierToJSON)),
        'delivery_year': value['deliveryYear'],
    };
}

