/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallments } from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallments';
import {
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsFromJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsFromJSONTyped,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsToJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsToJSONTyped,
} from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallments';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard {
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard
     */
    cvcToken?: string;
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallments}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard
     */
    installments?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallments;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard {
    if (json == null) {
        return json;
    }
    return {
        
        'cvcToken': json['cvc_token'] == null ? undefined : json['cvc_token'],
        'installments': json['installments'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsFromJSON(json['installments']),
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cvc_token': value['cvcToken'],
        'installments': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsToJSON(value['installments']),
    };
}

