/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInner } from './V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInner';
import {
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInnerFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInnerFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInnerToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInnerToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInner';
import type { V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions } from './V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions';
import {
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings {
    /**
     * 
     * @type {Array<V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInner>}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings
     */
    customFields?: Array<V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInner>;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings
     */
    defaultPaymentMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings
     */
    footer?: string;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings
     */
    renderingOptions?: V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptions;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettingsFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettingsFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'customFields': json['custom_fields'] == null ? undefined : ((json['custom_fields'] as Array<any>).map(V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInnerFromJSON)),
        'defaultPaymentMethod': json['default_payment_method'] == null ? undefined : json['default_payment_method'],
        'footer': json['footer'] == null ? undefined : json['footer'],
        'renderingOptions': json['rendering_options'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsFromJSON(json['rendering_options']),
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettingsToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettingsToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettingsToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_fields': value['customFields'] == null ? undefined : ((value['customFields'] as Array<any>).map(V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataCustomFieldsInnerToJSON)),
        'default_payment_method': value['defaultPaymentMethod'],
        'footer': value['footer'],
        'rendering_options': V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataRenderingOptionsToJSON(value['renderingOptions']),
    };
}

