/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOffline } from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOffline';
import {
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOfflineFromJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOfflineFromJSONTyped,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOfflineToJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOfflineToJSONTyped,
} from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOffline';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent {
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent
     */
    generatedCard?: string;
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOffline}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent
     */
    offline?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOffline;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresentFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresentFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresentFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedCard': json['generated_card'] == null ? undefined : json['generated_card'],
        'offline': json['offline'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOfflineFromJSON(json['offline']),
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresentToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresentToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresentToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardPresent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_card': value['generatedCard'],
        'offline': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentOfflineToJSON(value['offline']),
    };
}

