/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage {
    /**
     * 
     * @type {boolean}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage
     */
    supported?: boolean;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsageFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsageFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'supported': json['supported'] == null ? undefined : json['supported'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsageToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsageToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsageToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardThreeDSecureUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supported': value['supported'],
    };
}

