/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance {
    /**
     * 
     * @type {number}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance
     */
    key0?: number;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalanceFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalanceFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance {
    if (json == null) {
        return json;
    }
    return {
        
        'key0': json['key_0'] == null ? undefined : json['key_0'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalanceToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalanceToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalanceToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerInvoiceCreditBalance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_0': value['key0'],
    };
}

