/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ChargesChargeGet200Response } from './V1ChargesChargeGet200Response';
import {
    V1ChargesChargeGet200ResponseFromJSON,
    V1ChargesChargeGet200ResponseFromJSONTyped,
    V1ChargesChargeGet200ResponseToJSON,
    V1ChargesChargeGet200ResponseToJSONTyped,
} from './V1ChargesChargeGet200Response';
import type { V1ChargesPost200Response } from './V1ChargesPost200Response';
import {
    V1ChargesPost200ResponseFromJSON,
    V1ChargesPost200ResponseFromJSONTyped,
    V1ChargesPost200ResponseToJSON,
    V1ChargesPost200ResponseToJSONTyped,
} from './V1ChargesPost200Response';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet {
    /**
     * 
     * @type {V1ChargesPost200Response}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet
     */
    type?: V1ChargesPost200Response;
    /**
     * 
     * @type {V1ChargesChargeGet200Response}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet
     */
    applePay?: V1ChargesChargeGet200Response;
    /**
     * 
     * @type {V1ChargesPost200Response}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet
     */
    googlePay?: V1ChargesPost200Response;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWalletFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWalletFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : V1ChargesPost200ResponseFromJSON(json['type']),
        'applePay': json['apple_pay'] == null ? undefined : V1ChargesChargeGet200ResponseFromJSON(json['apple_pay']),
        'googlePay': json['google_pay'] == null ? undefined : V1ChargesPost200ResponseFromJSON(json['google_pay']),
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWalletToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWalletToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWalletToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromSetupAttemptPaymentMethodDetailsCardWallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': V1ChargesPost200ResponseToJSON(value['type']),
        'apple_pay': V1ChargesChargeGet200ResponseToJSON(value['applePay']),
        'google_pay': V1ChargesPost200ResponseToJSON(value['googlePay']),
    };
}

