/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan {
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan
     */
    interval?: string;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlanFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlanFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'count': json['count'] == null ? undefined : json['count'],
        'interval': json['interval'] == null ? undefined : json['interval'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlanToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlanToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlanToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodOptionsCardInstallmentsPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'count': value['count'],
        'interval': value['interval'],
    };
}

