/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds {
    /**
     * 
     * @type {number}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds
     */
    amountGte?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds
     */
    resetBillingCycleAnchor?: boolean;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholdsFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholdsFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds {
    if (json == null) {
        return json;
    }
    return {
        
        'amountGte': json['amount_gte'] == null ? undefined : json['amount_gte'],
        'resetBillingCycleAnchor': json['reset_billing_cycle_anchor'] == null ? undefined : json['reset_billing_cycle_anchor'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholdsToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholdsToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholdsToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingThresholds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_gte': value['amountGte'],
        'reset_billing_cycle_anchor': value['resetBillingCycleAnchor'],
    };
}

