/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible {
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible
     */
    prorationDiscounts?: string;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexibleFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexibleFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexibleFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible {
    if (json == null) {
        return json;
    }
    return {
        
        'prorationDiscounts': json['proration_discounts'] == null ? undefined : json['proration_discounts'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexibleToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexibleToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexibleToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerBillingModeFlexible | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proration_discounts': value['prorationDiscounts'],
    };
}

